"""Guards the output of tools/js_codemod/convert_dashboard.mjs staying in sync
with frontend/js/dashboard.js -- catches someone hand-editing the generated
bridge block later and drifting from the census, which the Wave 6.4 manifest
note this plan (docs/superpowers/plans/2026-08-06-dashboard-js-ast-module-
conversion.md) closes out was explicitly trying to prevent.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DASHBOARD_JS = ROOT / "frontend" / "js" / "dashboard.js"
INDEX_HTML = ROOT / "frontend" / "index.html"
CENSUS_REPORT = ROOT / "tools" / "js_codemod" / "census_report.json"
CONVERT_SCRIPT = ROOT / "tools" / "js_codemod" / "convert_dashboard.mjs"


def test_dashboard_js_loads_as_a_real_module():
    html = INDEX_HTML.read_text(encoding="utf-8")
    assert '<script type="module" src="js/dashboard.js' in html


def test_dashboard_js_never_contains_an_export_keyword():
    """Deliberate design choice (see convert_dashboard.mjs's module docstring):
    several tests eval() the whole file, or a literal-text slice of it, as
    plain non-module script -- `export` in any form is a SyntaxError there.
    Checked per-line (not a whole-file substring search) since "export" can
    legitimately appear inside a comment or string, e.g. "import/export
    adapter" -- that's prose, not a JS export statement."""
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    offending = [
        line for line in js.splitlines()
        if line.lstrip().startswith("export ") or line.lstrip().startswith("export{")
    ]
    assert offending == [], f"Found real export statement(s): {offending}"


def test_every_census_function_is_in_the_generated_window_bridge():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    marker = "Object.assign(window, {"
    assert marker in js
    bridge_block = js.split(marker, 1)[1].split("});", 1)[0]
    bridged_names = {n.strip() for n in bridge_block.replace("\n", " ").split(",") if n.strip()}
    reassigned = set(census["reassigned_functions"])
    value_copy_names = [n for n in census["functions"] if n not in reassigned]
    missing = [name for name in value_copy_names if name not in bridged_names]
    assert missing == [], f"Functions missing from the window bridge: {missing}"


def test_every_reassigned_function_and_referenced_variable_has_an_accessor():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    for name in [*census["reassigned_functions"], *census["externally_referenced_variables"]]:
        assert f'Object.defineProperty(window, {json.dumps(name)}, {{ get: () => {name}' in js, (
            f"{name} is missing its get accessor"
        )


def test_const_variables_get_a_get_only_accessor_never_a_setter():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    const_and_referenced = set(census["const_variables"]) & set(census["externally_referenced_variables"])
    assert const_and_referenced, "expected at least one const variable in the accessor set"
    for name in const_and_referenced:
        line = next(
            l for l in js.splitlines() if f'Object.defineProperty(window, {json.dumps(name)}' in l
        )
        assert "set:" not in line, f"{name} is const but got a setter: {line}"


def test_reassigned_functions_are_reassignable_let_bindings():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    for name in census["reassigned_functions"]:
        assert f"let {name} = function" in js or f"let {name} = async function" in js


def test_generated_block_has_the_do_not_hand_edit_header():
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    assert "AUTO-GENERATED by tools/js_codemod/convert_dashboard.mjs" in js
    assert "do not hand-edit" in js.lower() or "regenerate:" in js.lower()


def _run_check() -> subprocess.CompletedProcess:
    return subprocess.run(
        ["node", str(CONVERT_SCRIPT), "--check"],
        cwd=ROOT, text=True, capture_output=True, timeout=60,
    )


def test_codemod_check_mode_reports_no_drift():
    result = _run_check()
    assert result.returncode == 0, (
        "dashboard.js has drifted from the codemod's expected output "
        f"(hand-edited generated block, or a new top-level function/variable added "
        f"without regenerating census_report.json?):\n{result.stdout}{result.stderr}"
    )


@pytest.mark.parametrize("label,eol", [("LF", b"\n"), ("CRLF", b"\r\n")], ids=["lf", "crlf"])
def test_codemod_check_mode_is_line_ending_agnostic(label, eol):
    """--check must report drift on CONTENT differences only, never on line endings.

    The repo sets core.autocrlf=true and .gitattributes pins only *.csv and the
    plan-data manifest, so a Windows clone/worktree checks dashboard.js out as
    pure CRLF while Linux/CI gets pure LF. The codemod builds its generated
    window-bridge block with bare "\\n", so a byte-for-byte comparison against
    the CRLF file reported all ~265 generated lines as drift -- "dashboard.js is
    out of sync with the codemod" on every fresh Windows checkout, with zero
    real content drift and an empty `git diff`.

    A single-EOL assertion cannot catch this, because whichever flavour the
    running platform happens to check out is the one that passes. So drive both
    flavours explicitly: pre-fix this fails on Linux (the CRLF case) and on
    Windows (the CRLF case) alike.

    The file is restored byte-for-byte in `finally` -- this test rewrites a
    tracked source file and must never leave it altered, even on failure.
    """
    original = DASHBOARD_JS.read_bytes()
    rewritten = original.replace(b"\r\n", b"\n").replace(b"\n", eol)
    try:
        DASHBOARD_JS.write_bytes(rewritten)
        result = _run_check()
        assert result.returncode == 0, (
            f"--check reported drift on a pure-{label} copy of dashboard.js whose "
            f"content is byte-identical once line endings are normalized:\n"
            f"{result.stdout}{result.stderr}"
        )
    finally:
        DASHBOARD_JS.write_bytes(original)
    assert DASHBOARD_JS.read_bytes() == original, "dashboard.js was not restored"
