"""Guards the output of tools/js_codemod/convert_dashboard.mjs staying in sync
with frontend/js/dashboard.js -- catches someone hand-editing the generated
bridge block later and drifting from the census, which the Wave 6.4 manifest
note this plan (docs/superpowers/plans/2026-08-06-dashboard-js-ast-module-
conversion.md) closes out was explicitly trying to prevent.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DASHBOARD_JS = ROOT / "frontend" / "js" / "dashboard.js"
INDEX_HTML = ROOT / "frontend" / "index.html"
CENSUS_REPORT = ROOT / "tools" / "js_codemod" / "census_report.json"
CONVERT_SCRIPT = ROOT / "tools" / "js_codemod" / "convert_dashboard.mjs"


def test_dashboard_js_loads_as_a_real_module():
    html = INDEX_HTML.read_text(encoding="utf-8")
    assert '<script type="module" src="js/dashboard.js' in html


def test_dashboard_js_never_contains_an_export_keyword():
    """Deliberate design choice (see convert_dashboard.mjs's module docstring):
    several tests eval() the whole file, or a literal-text slice of it, as
    plain non-module script -- `export` in any form is a SyntaxError there.
    Checked per-line (not a whole-file substring search) since "export" can
    legitimately appear inside a comment or string, e.g. "import/export
    adapter" -- that's prose, not a JS export statement."""
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    offending = [
        line for line in js.splitlines()
        if line.lstrip().startswith("export ") or line.lstrip().startswith("export{")
    ]
    assert offending == [], f"Found real export statement(s): {offending}"


def test_every_census_function_is_in_the_generated_window_bridge():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    marker = "Object.assign(window, {"
    assert marker in js
    bridge_block = js.split(marker, 1)[1].split("});", 1)[0]
    bridged_names = {n.strip() for n in bridge_block.replace("\n", " ").split(",") if n.strip()}
    reassigned = set(census["reassigned_functions"])
    value_copy_names = [n for n in census["functions"] if n not in reassigned]
    missing = [name for name in value_copy_names if name not in bridged_names]
    assert missing == [], f"Functions missing from the window bridge: {missing}"


def test_every_reassigned_function_and_referenced_variable_has_an_accessor():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    for name in [*census["reassigned_functions"], *census["externally_referenced_variables"]]:
        assert f'Object.defineProperty(window, {json.dumps(name)}, {{ get: () => {name}' in js, (
            f"{name} is missing its get accessor"
        )


def test_const_variables_get_a_get_only_accessor_never_a_setter():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    const_and_referenced = set(census["const_variables"]) & set(census["externally_referenced_variables"])
    assert const_and_referenced, "expected at least one const variable in the accessor set"
    for name in const_and_referenced:
        line = next(
            l for l in js.splitlines() if f'Object.defineProperty(window, {json.dumps(name)}' in l
        )
        assert "set:" not in line, f"{name} is const but got a setter: {line}"


def test_reassigned_functions_are_reassignable_let_bindings():
    census = json.loads(CENSUS_REPORT.read_text(encoding="utf-8"))
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    for name in census["reassigned_functions"]:
        assert f"let {name} = function" in js or f"let {name} = async function" in js


def test_generated_block_has_the_do_not_hand_edit_header():
    js = DASHBOARD_JS.read_text(encoding="utf-8")
    assert "AUTO-GENERATED by tools/js_codemod/convert_dashboard.mjs" in js
    assert "do not hand-edit" in js.lower() or "regenerate:" in js.lower()


KNOWN_MANUAL_EXCEPTIONS = [
    # ytdTxColsCollapsed's get/set accessor (2026-08-06, "Wave 6.4
    # domain-module-split (row_model.js), plus fix the startup freeze it
    # caused") is a hand-added fix for a real live bug: it's assigned via an
    # inline onclick handler, a pattern census.mjs's cross-FILE reference
    # scan doesn't see (documented as a known follow-up in that commit).
    # Regenerating from the tool as-is silently drops this accessor and
    # reintroduces the startup freeze it fixes.
    'Object.defineProperty(window, "ytdTxColsCollapsed", '
    "{ get: () => ytdTxColsCollapsed, set: (v) => { ytdTxColsCollapsed = v; }, configurable: true });",
]


def test_codemod_check_mode_reports_no_drift():
    result = subprocess.run(
        ["node", str(CONVERT_SCRIPT), "--check"],
        cwd=ROOT, text=True, capture_output=True, timeout=60,
    )
    if result.returncode == 0:
        return
    # Confirm the ONLY drift is the known manual exception(s) above, not
    # blindly trust --check's binary result or blindly regenerate (which
    # would silently drop those hand-added fixes for real live bugs). Back
    # up the current (correct, hand-patched) file, let the tool regenerate
    # for real, diff line-by-line, then always restore the backup.
    original = DASHBOARD_JS.read_text(encoding="utf-8")
    try:
        regen = subprocess.run(
            ["node", str(CONVERT_SCRIPT)],
            cwd=ROOT, text=True, capture_output=True, timeout=60,
        )
        assert regen.returncode == 0, f"regeneration itself failed:\n{regen.stdout}{regen.stderr}"
        regenerated = DASHBOARD_JS.read_text(encoding="utf-8")
    finally:
        DASHBOARD_JS.write_text(original, encoding="utf-8")

    original_lines = set(original.splitlines())
    regenerated_lines = set(regenerated.splitlines())
    only_in_original = original_lines - regenerated_lines
    only_in_regenerated = regenerated_lines - original_lines
    assert not only_in_regenerated, (
        "the codemod's regenerated output has lines not in the committed "
        f"dashboard.js -- unexpected in either direction:\n{only_in_regenerated}"
    )
    unexplained = only_in_original - set(KNOWN_MANUAL_EXCEPTIONS)
    assert not unexplained, (
        "dashboard.js has drifted from the codemod's expected output in a way "
        "OTHER than the known manual exceptions in KNOWN_MANUAL_EXCEPTIONS above "
        f"(hand-edited generated block, or a new top-level function/variable added "
        f"without regenerating census_report.json?):\n{unexplained}"
    )
