#!/usr/bin/env node
// Converts frontend/js/dashboard.js into a real ES module: appends a
// generated window bridge (Object.assign value-copy for the ~758 functions
// that are only ever called externally; get+set Object.defineProperty
// accessors for the small number of functions another already-converted
// module reassigns as a monkey-patch decorator chain, and for every
// externally read/written top-level state variable). See the "Design
// correction" note in docs/superpowers/plans/2026-08-06-dashboard-js-ast-module-conversion.md
// for why a naive one-time Object.assign value copy alone is not safe for
// everything.
//
// Design note (2026-08-06, second correction): an EARLIER version of this
// codemod prefixed every one of the ~758 non-reassigned top-level function
// declarations with `export ` in place (`function foo(` -> `export function
// foo(`), and a later revision replaced that with a single trailing
// `export { name1, name2, ... };` list statement instead. Both turned out to
// be unnecessary AND actively harmful: `export` is not what makes
// dashboard.js's top-level bindings private to the module (that's
// `type="module"` on the script tag alone, regardless of whether anything is
// exported) -- nothing today does `import {x} from './dashboard.js'`, so
// `export` anywhere in this file had zero effect on the actual backward-compat
// mechanism, which is entirely the window bridge below. Meanwhile several
// tests eval() the WHOLE file (or a large slice of it, extracted by literal
// text search) as a plain non-module script to smoke-test its runtime
// behavior -- `export`, in ANY form or position, is a SyntaxError in that
// context. So: no `export` keyword anywhere, ever, in this file. Only the 2
// reassigned functions get their own declaration rewritten (`function
// name(){}` -> `let name = function(){}`, so they're reassignable at all,
// with no `export` prefix) -- that collateral risk was checked directly
// (grep for their exact names in tests/) and found clean.
//
// Transform strategy: use the AST purely to DISCOVER exact character offsets
// of the 2 reassigned function declarations, then splice the source STRING
// directly at those offsets. This guarantees every untouched byte of the
// file's ~19,000 lines is preserved exactly -- unlike asking a printer
// (recast/jscodeshift's .toSource()) to re-print a newly-constructed wrapper
// AST node, which inserts its own formatting (e.g. a blank line before/after)
// even when reusing the original inner node's text.
//
// PARSER CHOICE -- load-bearing, do not "simplify" this back to jscodeshift.
// Because the strategy above splices the source STRING at AST-discovered byte
// offsets, those offsets must be true byte offsets.
// jscodeshift.withParser("babel") reports node.start/node.end as though every
// newline were two characters, so it is only correct on a CRLF source.
// Measured against this repo's own dashboard.js: CRLF -> all 584 top-level
// functions slice correctly; the identical file LF-normalised -> ALL 584 slice
// wrong. This repo has core.autocrlf=true and .gitattributes pins only *.csv
// and input/plan_data_manifest.json to eol=lf -- nothing covers *.js -- so a
// Windows checkout is CRLF and a Linux/macOS/CI checkout is LF, where this
// codemod would splice `let renderMain = ...` into the middle of an unrelated
// function. recast's node.loc is not a fallback: it is null for a declaration
// nested inside an `export`. Plain @babel/parser reports true offsets under
// both line endings. Guarded by
// tests/frontend/js_codemod_parser_offsets.test.mjs. Same choice as
// extract_module.mjs, extract_core.mjs and find_clusters.mjs.
//
// Usage:
//   node tools/js_codemod/convert_dashboard.mjs          (writes the file)
//   node tools/js_codemod/convert_dashboard.mjs --check  (exit 1 if it would change anything)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as babelParser from "@babel/parser";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");
const DASHBOARD_PATH = path.join(ROOT, "frontend", "js", "dashboard.js");
const CENSUS_PATH = path.join(__dirname, "census_report.json");

const START_MARKER = "// AUTO-GENERATED by tools/js_codemod/convert_dashboard.mjs";

function stripExistingGeneratedBlock(source) {
  const idx = source.indexOf(START_MARKER);
  return idx === -1 ? source : source.slice(0, idx).replace(/\s*$/, "\n");
}

function findReassignedTopLevelFunctions(source, reassignedFunctions) {
  const reassigned = new Set(reassignedFunctions);
  const program = babelParser.parse(source, { sourceType: "module" }).program;
  const found = [];
  for (const stmt of program.body) {
    if (stmt.type === "FunctionDeclaration" && stmt.id && reassigned.has(stmt.id.name)) {
      found.push({ name: stmt.id.name, start: stmt.start, end: stmt.end, async: stmt.async });
    }
  }
  return found;
}

function applyTextSplices(source, reassignedFns) {
  // Process from the END of the file backwards so earlier offsets are
  // unaffected by edits made at later offsets. Only the reassigned functions
  // (renderMain, showStepHelp) get their declaration rewritten -- every other
  // function is untouched (see the module-level comment for why).
  const sorted = [...reassignedFns].sort((a, b) => b.start - a.start);
  let text = source;

  for (const fn of sorted) {
    const before = text.slice(0, fn.start);
    const body = text.slice(fn.start, fn.end);
    const after = text.slice(fn.end);

    // `function name(...) {...}` -> `let name = function(...) {...};`
    // (or `async function name(...)` -> `... = async function(...) {...};`)
    const anonymized = body.replace(/^(async\s+)?function\s+[A-Za-z0-9_$]+/, "$1function");
    text = `${before}let ${fn.name} = ${anonymized};${after}`;
  }

  return text;
}

function buildGeneratedBlock(census) {
  const { functions, reassigned_functions, externally_referenced_variables, const_variables } = census;
  const reassignedSet = new Set(reassigned_functions);
  const constSet = new Set(const_variables || []);
  const accessorNames = [...reassigned_functions, ...externally_referenced_variables].sort();
  const valueCopyFunctions = functions.filter((name) => !reassignedSet.has(name));

  const accessorLines = accessorNames.map((name) => {
    // const bindings can never be reassigned -- a setter that does `name = v`
    // is a guaranteed runtime TypeError ("Assignment to constant variable")
    // if ever invoked, even though it would parse fine and sit unused today.
    // reassigned_functions never contains a const (functions are `function`
    // declarations, not const bindings), so this only applies to variables.
    if (constSet.has(name)) {
      return `Object.defineProperty(window, ${JSON.stringify(name)}, { get: () => ${name}, configurable: true });`;
    }
    return `Object.defineProperty(window, ${JSON.stringify(name)}, { get: () => ${name}, set: (v) => { ${name} = v; }, configurable: true });`;
  });

  const wrapped = [];
  let line = "";
  for (const name of valueCopyFunctions) {
    const piece = name + ", ";
    if ((line + piece).length > 100) {
      wrapped.push("  " + line.trimEnd());
      line = "";
    }
    line += piece;
  }
  if (line) wrapped.push("  " + line.trimEnd());

  return [
    START_MARKER,
    "// Regenerate: node tools/js_codemod/census.mjs && node tools/js_codemod/convert_dashboard.mjs",
    "// get+set accessors: reassigned functions (monkey-patch decorator chains) and",
    "// externally read/written state variables. Object.assign below: every other",
    "// top-level function, safe as a one-time value copy since it's never reassigned.",
    "// Deliberately NO `export` statement anywhere in this file: nothing today",
    "// does `import {x} from './dashboard.js'`, and several tests eval() the",
    "// whole file (or a large slice of it) as a plain non-module script to",
    "// smoke-test its runtime behavior -- any `export` keyword anywhere is a",
    "// SyntaxError in that context. type=\"module\" on the script tag alone (not",
    "// any export statement) is what makes this file's top-level bindings",
    "// private; the bridge below is the entire backward-compat mechanism.",
    ...accessorLines,
    "Object.assign(window, {",
    ...wrapped,
    "});",
    "",
  ].join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const census = JSON.parse(fs.readFileSync(CENSUS_PATH, "utf8"));
  const original = fs.readFileSync(DASHBOARD_PATH, "utf8");
  const withoutGenerated = stripExistingGeneratedBlock(original);
  const reassignedFns = findReassignedTopLevelFunctions(withoutGenerated, census.reassigned_functions);
  const spliced = applyTextSplices(withoutGenerated, reassignedFns);
  const generatedBlock = buildGeneratedBlock(census);
  const next = spliced.replace(/\s*$/, "\n") + "\n" + generatedBlock;

  if (check) {
    if (next !== original) {
      console.error("dashboard.js is out of sync with the codemod. Run without --check to fix.");
      process.exitCode = 1;
    } else {
      console.log("dashboard.js matches the codemod's expected output.");
    }
    return;
  }

  fs.writeFileSync(DASHBOARD_PATH, next, "utf8");
  const totalAccessors = census.reassigned_functions.length + census.externally_referenced_variables.length;
  const constAccessors = (census.const_variables || []).filter((n) =>
    census.externally_referenced_variables.includes(n),
  ).length;
  console.log(
    `Wrote ${DASHBOARD_PATH}: ${census.functions.length - census.reassigned_functions.length} functions ` +
      `value-copy bridged, ${totalAccessors} accessors generated (${constAccessors} get-only for const, ` +
      `${totalAccessors - constAccessors} get+set).`,
  );
}

main();
