#!/usr/bin/env node
// Splits top-level declarations out of frontend/js/dashboard.js into a new ES
// module, and PROVES it moved them without altering them.
//
// Why a tool instead of hand-editing: the predecessor pass
// (docs/superpowers/plans/2026-08-06-dashboard-js-ast-module-conversion.md)
// established that hand-editing this file at scale is not a responsible
// approach for production financial software. The holdings leaf was moved by
// hand because it was one self-contained block; the remaining ~10-15 domain
// clusters are not.
//
// Transform strategy (same as convert_dashboard.mjs and extract_core.mjs): use
// the AST purely to DISCOVER exact character offsets, then splice the source
// STRING at those offsets. Asking a printer (recast/jscodeshift .toSource()) to
// re-emit the file would reformat untouched code.
//
// The verification is the point of this tool. After writing the new module it
// reads that module BACK OFF DISK, recovers each moved declaration's text from
// the written file's own AST, and reconstructs the original dashboard.js from
// (post-removal dashboard.js + those recovered texts). Deriving the texts from
// the OUTPUT rather than from the in-memory original is what makes this a real
// check instead of a tautology: it is what catches a mangled `export ` prefix,
// a reordering bug, a wrong byte range, or a newline-handling error.
//
// PARSER CHOICE -- this is load-bearing, do not "simplify" it back to
// jscodeshift. Every other tool in this directory uses
// jscodeshift.withParser("babel") and reads node.start/node.end as byte
// offsets. Those offsets are only correct when the file on disk uses CRLF line
// endings. Measured against this repo's own dashboard.js: with CRLF, all 584
// top-level functions slice correctly; with the identical file LF-normalised,
// ALL 584 slice wrong -- every extracted "function" is garbage taken from the
// middle of unrelated code, because the offsets are reported as though each
// newline were two characters. That is not a theoretical concern: this repo
// has core.autocrlf=true and .gitattributes pins only *.csv to eol=lf, so a
// Windows checkout is CRLF and a Linux/CI checkout is LF. Plain @babel/parser
// reports true offsets under both, verified the same way. recast's node.loc is
// also unusable here -- it is null on a declaration inside an export.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import * as babelParser from "@babel/parser";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");
const DASHBOARD_PATH = path.join(ROOT, "frontend", "js", "dashboard.js");
const CENSUS_PATH = path.join(__dirname, "census_report.json");
const JS_DIR = path.join(ROOT, "frontend", "js");
const INDEX_HTML_PATH = path.join(ROOT, "frontend", "index.html");
const BRIDGE_MARKER = "// AUTO-GENERATED by tools/js_codemod/convert_dashboard.mjs";

function parseProgram(source) {
  return babelParser.parse(source, { sourceType: "module" }).program;
}

function die(message) {
  console.error("ABORT: " + message);
  process.exit(1);
}

function parseArgs(argv) {
  const out = { names: null, out: null, headerFile: null, check: false };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--names") out.names = argv[++i];
    else if (argv[i] === "--out") out.out = argv[++i];
    else if (argv[i] === "--header-file") out.headerFile = argv[++i];
    else if (argv[i] === "--check") out.check = true;
    else die(`unknown argument ${argv[i]}`);
  }
  if (!out.names) die("--names is required");
  if (!out.out) die("--out is required");
  return out;
}

// One entry per top-level statement that declares something. `names` holds
// EVERY name the statement declares, because `let a = 1, b = 2;` is a single
// splice unit -- moving `a` necessarily moves `b`.
// Unwraps `export <decl>` so this works on both dashboard.js (never exports)
// and a generated module (exports everything).
function collectTopLevelStatements(source) {
  const program = parseProgram(source);
  const statements = [];
  for (const raw of program.body) {
    const stmt =
      raw.type === "ExportNamedDeclaration" && raw.declaration ? raw.declaration : raw;
    if (stmt.type === "FunctionDeclaration" && stmt.id) {
      statements.push({
        names: [stmt.id.name], start: stmt.start, end: stmt.end, kind: "function",
      });
    } else if (stmt.type === "VariableDeclaration") {
      const names = [];
      let everyInitIsFunction = stmt.declarations.length > 0;
      for (const decl of stmt.declarations) {
        if (decl.id.type !== "Identifier") { everyInitIsFunction = false; continue; }
        names.push(decl.id.name);
        const isFn = decl.init &&
          (decl.init.type === "FunctionExpression" || decl.init.type === "ArrowFunctionExpression");
        if (!isFn) everyInitIsFunction = false;
      }
      if (names.length) {
        statements.push({
          names, start: stmt.start, end: stmt.end,
          kind: everyInitIsFunction ? "function" : "variable",
          declKind: stmt.kind,
        });
      }
    }
  }
  return statements;
}

function stripBridge(source) {
  const idx = source.indexOf(BRIDGE_MARKER);
  return idx === -1 ? source : source.slice(0, idx);
}

function otherFileSources(outAbs) {
  const sources = [];
  for (const entry of fs.readdirSync(JS_DIR)) {
    const full = path.join(JS_DIR, entry);
    if (!entry.endsWith(".js")) continue;
    if (full === DASHBOARD_PATH || full === outAbs) continue;
    sources.push([path.relative(ROOT, full), fs.readFileSync(full, "utf8")]);
  }
  sources.push(["frontend/index.html", fs.readFileSync(INDEX_HTML_PATH, "utf8")]);
  return sources;
}

function validate(source, requested, outAbs) {
  const census = JSON.parse(fs.readFileSync(CENSUS_PATH, "utf8"));
  const statements = collectTopLevelStatements(source);
  const byName = new Map();
  for (const st of statements) for (const n of st.names) byName.set(n, st);

  const seen = new Set();
  const duplicates = requested.filter((n) => (seen.has(n) ? true : (seen.add(n), false)));
  if (duplicates.length) die(`duplicate name(s) in --names: ${[...new Set(duplicates)].join(", ")}`);

  const missing = requested.filter((n) => !byName.has(n));
  if (missing.length) {
    die(`not a top-level declaration in dashboard.js: ${missing.join(", ")}`);
  }

  const reassigned = requested.filter((n) => census.reassigned_functions.includes(n));
  if (reassigned.length) {
    die(
      `refusing to move reassigned function(s): ${reassigned.join(", ")}. ` +
        "Other leaf modules monkey-patch these as a decorator chain, which needs the " +
        "reassignable-let + get/set accessor treatment convert_dashboard.mjs applies " +
        "inside dashboard.js. This tool does not reproduce that for a target module.",
    );
  }

  const requestedSet = new Set(requested);
  const chosen = [...new Set(requested.map((n) => byName.get(n)))];
  for (const st of chosen) {
    const strays = st.names.filter((n) => !requestedSet.has(n));
    if (strays.length) {
      die(
        `${st.names.filter((n) => requestedSet.has(n)).join(", ")} shares one declaration ` +
          `statement with ${strays.join(", ")}, which was not requested. Splicing is ` +
          "per-statement, so request all of them or none.",
      );
    }
  }

  // Variable safety rule. Functions are EXPECTED to still be called from
  // dashboard.js -- the window bridge exists for exactly that. Variables are
  // not: a moved variable becomes module-private, and dashboard.js's generated
  // bridge cannot expose a binding that no longer lives in dashboard.js. So a
  // variable may only move if nothing else anywhere still reads it.
  let afterPreview = source;
  for (const st of [...chosen].sort((a, b) => b.start - a.start)) {
    afterPreview = afterPreview.slice(0, st.start) + afterPreview.slice(st.end);
  }
  const afterNoBridge = stripBridge(afterPreview);
  const others = otherFileSources(outAbs);
  for (const st of chosen) {
    if (st.kind !== "variable") continue;
    for (const name of st.names) {
      const re = new RegExp(`\\b${name}\\b`);
      if (re.test(afterNoBridge)) {
        die(
          `${name} is still referenced in dashboard.js after removal, so it is shared ` +
            "state and must stay behind. Leave it out of --names; the generated window " +
            "bridge will expose it to the new module.",
        );
      }
      for (const [label, text] of others) {
        if (re.test(text)) {
          die(`${name} is referenced by ${label}, so it is shared state and must stay behind.`);
        }
      }
    }
  }
  return chosen.sort((a, b) => a.start - b.start);
}

// Cut each chosen statement out, consuming the single trailing newline that
// follows it so the removal does not leave a blank line behind. Records
// exactly how many bytes each removal took, which the reconstruction below
// needs to walk the post-removal string.
// Handles CRLF and LF alike: this repo checks out CRLF on Windows and LF on
// Linux/CI, so a hardcoded "\n" would silently leave a stray blank line behind
// on every Windows removal.
function trailingNewline(source, end) {
  if (source.startsWith("\r\n", end)) return "\r\n";
  if (source[end] === "\n") return "\n";
  return "";
}

function removeStatements(source, chosen) {
  let after = source;
  for (const st of [...chosen].sort((a, b) => b.start - a.start)) {
    const end = st.end + trailingNewline(source, st.end).length;
    after = after.slice(0, st.start) + after.slice(end);
  }
  const moved = chosen.map((st) => {
    const newline = trailingNewline(source, st.end);
    return {
      names: st.names,
      start: st.start,
      text: source.slice(st.start, st.end),
      newline,
      removedLen: st.end - st.start + newline.length,
    };
  });
  return { after, moved };
}

function buildModule(headerText, moved) {
  const bodies = moved.map((m) => `export ${m.text}`).join("\n\n");
  const allNames = moved.flatMap((m) => m.names);
  const bridge =
    "\n\n// Every export above is also re-attached to window: dashboard.js calls these\n" +
    "// as bare globals, and this file's own rendered HTML uses inline\n" +
    '// onclick="..." handlers, which always resolve through window regardless of\n' +
    "// module scoping. New code should prefer `import` from this module; this\n" +
    "// bridge exists only for callers that cannot move to import in the same pass.\n" +
    "Object.assign(window, {\n" +
    allNames.map((n) => `  ${n},`).join("\n") +
    "\n});\n";
  return headerText.replace(/\s*$/, "\n") + "\n" + bodies + bridge;
}

// Recover each moved declaration's text from the WRITTEN module file's own AST.
// Returns a Map from the joined name key to the declaration source text with
// the `export ` prefix removed.
function recoverFromModule(moduleSource) {
  const program = parseProgram(moduleSource);
  const recovered = new Map();
  for (const stmt of program.body) {
    if (stmt.type !== "ExportNamedDeclaration" || !stmt.declaration) continue;
    const decl = stmt.declaration;
    const names = [];
    if (decl.type === "FunctionDeclaration" && decl.id) names.push(decl.id.name);
    else if (decl.type === "VariableDeclaration") {
      for (const d of decl.declarations) if (d.id.type === "Identifier") names.push(d.id.name);
    }
    if (names.length) recovered.set(names.join(","), moduleSource.slice(decl.start, decl.end));
  }
  return recovered;
}

// Rebuild the original file from (post-removal source + texts recovered from
// the written module). Walks ascending, translating each original offset into
// its position in the shortened string by subtracting everything removed
// before it. Returns null (rather than exiting) if the module is missing a
// declaration, so the caller can roll back before reporting.
function reconstruct(after, moved, recovered) {
  let out = "";
  let cursor = 0;
  let removedSoFar = 0;
  for (const m of [...moved].sort((a, b) => a.start - b.start)) {
    const key = m.names.join(",");
    if (!recovered.has(key)) return null;
    const cut = m.start - removedSoFar;
    out += after.slice(cursor, cut);
    out += recovered.get(key) + m.newline;
    cursor = cut;
    removedSoFar += m.removedLen;
  }
  out += after.slice(cursor);
  return out;
}

function topLevelNames(source) {
  return new Set(collectTopLevelStatements(source).flatMap((st) => st.names));
}

function nodeSyntaxCheck(filePath) {
  // The repo's package.json sets "type": "module", so `node --check` parses
  // .js files here with the ESM goal and accepts `export`. Verified against
  // both dashboard.js (export-free) and dashboard_decomp_row_model.js.
  try {
    execFileSync(process.execPath, ["--check", filePath], { stdio: "pipe" });
    return null;
  } catch (err) {
    return String(err.stderr || err.message);
  }
}

function main() {
  const args = parseArgs(process.argv);
  const requested = args.names.split(",").map((s) => s.trim()).filter(Boolean);
  const outAbs = path.resolve(ROOT, args.out);
  const source = fs.readFileSync(DASHBOARD_PATH, "utf8");

  const chosen = validate(source, requested, outAbs);
  const { after, moved } = removeStatements(source, chosen);

  const headerText = args.headerFile
    ? fs.readFileSync(path.resolve(ROOT, args.headerFile), "utf8")
    : "// Extracted from dashboard.js by tools/js_codemod/extract_module.mjs.";
  const moduleSource = buildModule(headerText, moved);

  // In check mode the module still has to hit the disk -- the round-trip
  // verification is only meaningful if it reads back what was actually
  // written -- but it goes to a sibling temp path and dashboard.js is never
  // touched.
  // Keep the .js extension on the temp path -- `node --check` refuses an
  // unknown extension (ERR_UNKNOWN_FILE_EXTENSION), which would make check
  // mode fail for a reason that has nothing to do with the code.
  const modulePath = args.check ? outAbs.replace(/\.js$/, "") + ".check-tmp.js" : outAbs;
  fs.writeFileSync(modulePath, moduleSource, "utf8");
  if (!args.check) fs.writeFileSync(DASHBOARD_PATH, after, "utf8");

  const rollback = (message) => {
    if (!args.check) fs.writeFileSync(DASHBOARD_PATH, source, "utf8");
    try { fs.unlinkSync(modulePath); } catch { /* already gone */ }
    die(message);
  };

  const writtenModule = fs.readFileSync(modulePath, "utf8");
  const recovered = recoverFromModule(writtenModule);

  const rebuilt = reconstruct(after, moved, recovered);
  if (rebuilt === null) {
    rollback("the written module is missing one of the declarations it should contain");
  }
  if (rebuilt !== source) {
    let at = 0;
    while (at < rebuilt.length && at < source.length && rebuilt[at] === source[at]) at++;
    rollback(
      "round-trip verification FAILED: reconstructing dashboard.js from the written " +
        `module does not reproduce the original. First difference at byte ${at}: ` +
        `expected ${JSON.stringify(source.slice(at, at + 60))} ` +
        `but got ${JSON.stringify(rebuilt.slice(at, at + 60))}`,
    );
  }

  const movedNames = new Set(moved.flatMap((m) => m.names));
  const expectedDashboard = new Set([...topLevelNames(source)].filter((n) => !movedNames.has(n)));
  const actualDashboard = topLevelNames(after);
  const lostFromDashboard = [...expectedDashboard].filter((n) => !actualDashboard.has(n));
  const gainedInDashboard = [...actualDashboard].filter((n) => !expectedDashboard.has(n));
  if (lostFromDashboard.length || gainedInDashboard.length) {
    rollback(
      `inventory verification FAILED for dashboard.js: unexpectedly removed ` +
        `[${lostFromDashboard.join(", ")}], unexpectedly present [${gainedInDashboard.join(", ")}]`,
    );
  }
  const actualModule = new Set([...recovered.keys()].flatMap((k) => k.split(",")));
  const missingFromModule = [...movedNames].filter((n) => !actualModule.has(n));
  const extraInModule = [...actualModule].filter((n) => !movedNames.has(n));
  if (missingFromModule.length || extraInModule.length) {
    rollback(
      `inventory verification FAILED for the new module: missing ` +
        `[${missingFromModule.join(", ")}], unexpected [${extraInModule.join(", ")}]`,
    );
  }

  const moduleErr = nodeSyntaxCheck(modulePath);
  if (moduleErr) rollback("the generated module is not valid JavaScript:\n" + moduleErr);
  if (!args.check) {
    const dashErr = nodeSyntaxCheck(DASHBOARD_PATH);
    if (dashErr) rollback("the rewritten dashboard.js is not valid JavaScript:\n" + dashErr);
  }

  if (args.check) {
    fs.unlinkSync(modulePath);
    console.log(
      `CHECK PASSED: ${moved.length} statement(s) / ${movedNames.size} name(s) would move ` +
        `to ${args.out}. Nothing was written.`,
    );
    return;
  }

  console.log(`EXTRACTED ${movedNames.size} declaration(s) to ${args.out}`);
  console.log(`dashboard.js is now ${after.split("\n").length} lines.`);
  console.log("\nRequired follow-up (this tool deliberately does NOT do these):");
  console.log(`  1. Add <script type="module" src="js/${path.basename(args.out)}?v=1"></script>`);
  console.log("     to frontend/index.html IMMEDIATELY BEFORE the dashboard.js tag.");
  console.log("  2. node tools/js_codemod/census.mjs");
  console.log("  3. node tools/js_codemod/convert_dashboard.mjs");
  console.log("  4. Add a manifest entry to frontend/js/modules/phase3_module_manifest.js");
  console.log("  5. Lower DASHBOARD_JS_MAX_LINES in tests/test_frontend_size_ratchet.py");
}

main();
