#!/usr/bin/env node
// Splits top-level declarations out of frontend/js/dashboard.js into a new ES
// module, and PROVES it moved them without altering them.
//
// Why a tool instead of hand-editing: the predecessor pass
// (docs/superpowers/plans/2026-08-06-dashboard-js-ast-module-conversion.md)
// established that hand-editing this file at scale is not a responsible
// approach for production financial software. The holdings leaf was moved by
// hand because it was one self-contained block; the remaining ~10-15 domain
// clusters are not.
//
// Transform strategy (same as convert_dashboard.mjs and extract_core.mjs): use
// the AST purely to DISCOVER exact character offsets, then splice the source
// STRING at those offsets. Asking a printer (recast/jscodeshift .toSource()) to
// re-emit the file would reformat untouched code.
//
// The verification is the point of this tool. After writing the new module it
// reads that module BACK OFF DISK, recovers each moved declaration's text from
// the written file's own AST, and reconstructs the original dashboard.js from
// (post-removal dashboard.js + those recovered texts). Deriving the texts from
// the OUTPUT rather than from the in-memory original is what makes this a real
// check instead of a tautology: it is what catches a mangled `export ` prefix,
// a reordering bug, a wrong byte range, or a newline-handling error.
//
// Usage:
//   node tools/js_codemod/extract_module.mjs --names a,b,c --out frontend/js/dashboard_decomp_x.js --header-file hdr.txt
//   node tools/js_codemod/extract_module.mjs --names a,b,c --out ... --check   (dry run, writes nothing to the real paths)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import jscodeshift from "jscodeshift";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");
const DASHBOARD_PATH = path.join(ROOT, "frontend", "js", "dashboard.js");
const CENSUS_PATH = path.join(__dirname, "census_report.json");
const JS_DIR = path.join(ROOT, "frontend", "js");
const INDEX_HTML_PATH = path.join(ROOT, "frontend", "index.html");
const BRIDGE_MARKER = "// AUTO-GENERATED by tools/js_codemod/convert_dashboard.mjs";
const j = jscodeshift.withParser("babel");

function die(message) {
  console.error("ABORT: " + message);
  process.exit(1);
}

function parseArgs(argv) {
  const out = { names: null, out: null, headerFile: null, check: false };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--names") out.names = argv[++i];
    else if (argv[i] === "--out") out.out = argv[++i];
    else if (argv[i] === "--header-file") out.headerFile = argv[++i];
    else if (argv[i] === "--check") out.check = true;
    else die(`unknown argument ${argv[i]}`);
  }
  if (!out.names) die("--names is required");
  if (!out.out) die("--out is required");
  return out;
}

// One entry per top-level statement that declares something. `names` holds
// EVERY name the statement declares, because `let a = 1, b = 2;` is a single
// splice unit -- moving `a` necessarily moves `b`.
function collectTopLevelStatements(source) {
  const root = j(source);
  const statements = [];
  root.find(j.Program).forEach((programPath) => {
    for (const stmt of programPath.node.body) {
      if (stmt.type === "FunctionDeclaration" && stmt.id) {
        statements.push({
          names: [stmt.id.name], start: stmt.start, end: stmt.end, kind: "function",
        });
      } else if (stmt.type === "VariableDeclaration") {
        const names = [];
        let everyInitIsFunction = stmt.declarations.length > 0;
        for (const decl of stmt.declarations) {
          if (decl.id.type !== "Identifier") { everyInitIsFunction = false; continue; }
          names.push(decl.id.name);
          const isFn = decl.init &&
            (decl.init.type === "FunctionExpression" || decl.init.type === "ArrowFunctionExpression");
          if (!isFn) everyInitIsFunction = false;
        }
        if (names.length) {
          statements.push({
            names, start: stmt.start, end: stmt.end,
            kind: everyInitIsFunction ? "function" : "variable",
            declKind: stmt.kind,
          });
        }
      }
    }
  });
  return statements;
}

function stripBridge(source) {
  const idx = source.indexOf(BRIDGE_MARKER);
  return idx === -1 ? source : source.slice(0, idx);
}

function otherFileSources(outAbs) {
  const sources = [];
  for (const entry of fs.readdirSync(JS_DIR)) {
    const full = path.join(JS_DIR, entry);
    if (!entry.endsWith(".js")) continue;
    if (full === DASHBOARD_PATH || full === outAbs) continue;
    sources.push([path.relative(ROOT, full), fs.readFileSync(full, "utf8")]);
  }
  sources.push(["frontend/index.html", fs.readFileSync(INDEX_HTML_PATH, "utf8")]);
  return sources;
}

function validate(source, requested, outAbs) {
  const census = JSON.parse(fs.readFileSync(CENSUS_PATH, "utf8"));
  const statements = collectTopLevelStatements(source);
  const byName = new Map();
  for (const st of statements) for (const n of st.names) byName.set(n, st);

  const seen = new Set();
  const duplicates = requested.filter((n) => (seen.has(n) ? true : (seen.add(n), false)));
  if (duplicates.length) die(`duplicate name(s) in --names: ${[...new Set(duplicates)].join(", ")}`);

  const missing = requested.filter((n) => !byName.has(n));
  if (missing.length) {
    die(`not a top-level declaration in dashboard.js: ${missing.join(", ")}`);
  }

  const reassigned = requested.filter((n) => census.reassigned_functions.includes(n));
  if (reassigned.length) {
    die(
      `refusing to move reassigned function(s): ${reassigned.join(", ")}. ` +
        "Other leaf modules monkey-patch these as a decorator chain, which needs the " +
        "reassignable-let + get/set accessor treatment convert_dashboard.mjs applies " +
        "inside dashboard.js. This tool does not reproduce that for a target module.",
    );
  }

  const requestedSet = new Set(requested);
  const chosen = [...new Set(requested.map((n) => byName.get(n)))];
  for (const st of chosen) {
    const strays = st.names.filter((n) => !requestedSet.has(n));
    if (strays.length) {
      die(
        `${st.names.filter((n) => requestedSet.has(n)).join(", ")} shares one declaration ` +
          `statement with ${strays.join(", ")}, which was not requested. Splicing is ` +
          "per-statement, so request all of them or none.",
      );
    }
  }

  // Variable safety rule. Functions are EXPECTED to still be called from
  // dashboard.js -- the window bridge exists for exactly that. Variables are
  // not: a moved variable becomes module-private, and dashboard.js's generated
  // bridge cannot expose a binding that no longer lives in dashboard.js. So a
  // variable may only move if nothing else anywhere still reads it.
  let afterPreview = source;
  for (const st of [...chosen].sort((a, b) => b.start - a.start)) {
    afterPreview = afterPreview.slice(0, st.start) + afterPreview.slice(st.end);
  }
  const afterNoBridge = stripBridge(afterPreview);
  const others = otherFileSources(outAbs);
  for (const st of chosen) {
    if (st.kind !== "variable") continue;
    for (const name of st.names) {
      const re = new RegExp(`\\b${name}\\b`);
      if (re.test(afterNoBridge)) {
        die(
          `${name} is still referenced in dashboard.js after removal, so it is shared ` +
            "state and must stay behind. Leave it out of --names; the generated window " +
            "bridge will expose it to the new module.",
        );
      }
      for (const [label, text] of others) {
        if (re.test(text)) {
          die(`${name} is referenced by ${label}, so it is shared state and must stay behind.`);
        }
      }
    }
  }
  return chosen.sort((a, b) => a.start - b.start);
}

function main() {
  const args = parseArgs(process.argv);
  const requested = args.names.split(",").map((s) => s.trim()).filter(Boolean);
  const outAbs = path.resolve(ROOT, args.out);
  const source = fs.readFileSync(DASHBOARD_PATH, "utf8");
  const chosen = validate(source, requested, outAbs);
  console.log(`validation passed: ${chosen.length} statement(s), ${requested.length} name(s).`);
}

main();
