#!/usr/bin/env node
// Runs the deterministic follow-up that tools/js_codemod/extract_module.mjs
// deliberately does NOT run, and then verifies the result.
//
// Why this exists: extract_module.mjs ends by printing a five-step checklist
// (wire index.html, re-run census, re-run convert_dashboard, add a manifest
// entry, lower the size ratchet). Those steps are mechanical and identical
// every pass, but doing them by hand costs about a dozen error-prone edits per
// cluster and there are roughly a dozen clusters left. Worse, the checklist is
// incomplete in two ways that only show up once you have actually done a pass:
// it never mentions regenerating clusters_report.json (stale the moment an
// extraction lands, and the next pass reads it to pick its cluster), and it
// never verifies the thing most likely to be silently wrong -- that every
// dashboard.js binding the new module reaches back for is actually exposed on
// the window bridge, with a SETTER for the ones the module assigns to.
//
// That last check is the reason this is a tool and not a shell alias. Module
// code is strict, so `someDashboardLet = x` from inside an extracted module is
// a ReferenceError unless the bridge has already defined that property on
// window with a set accessor. It resolves at call time, not load time, so a
// missing setter does not fail `node --check`, does not fail the round-trip
// check, and does not fail a page load -- it fails later, when a user edits a
// field. Nothing else in the pipeline looks for it.
//
// This tool does NOT touch tests that assert against dashboard.js source text,
// and does not try to. Those breakages need judgement (see the report it
// prints at the end).
//
// PARSER CHOICE -- same constraint as extract_module.mjs, do not "simplify"
// this to jscodeshift. jscodeshift's node.start/node.end are only valid byte
// offsets on a CRLF source; on an LF checkout (Linux/CI) they are all wrong.
// Plain @babel/parser reports true offsets under both.
//
// LINE ENDINGS -- every file this edits is read, modified and written as a
// string, and inserted lines use the EOL already present in that file. This
// repo has core.autocrlf=true, so the same file is CRLF on a Windows checkout
// and LF on CI; hardcoding "\n" would leave a mixed-ending file that shows up
// as a whole-file diff on the other platform.
//
// Usage:
//   node tools/js_codemod/finish_extraction.mjs --module frontend/js/dashboard_decomp_x.js
//   node tools/js_codemod/finish_extraction.mjs --module ... --manifest-file tools/js_codemod/headers/x_manifest.txt
//   node tools/js_codemod/finish_extraction.mjs --module ... --check   (report only, writes nothing)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import * as babelParser from "@babel/parser";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");
const DASHBOARD_PATH = path.join(ROOT, "frontend", "js", "dashboard.js");
const INDEX_HTML_PATH = path.join(ROOT, "frontend", "index.html");
const MANIFEST_PATH = path.join(ROOT, "frontend", "js", "modules", "phase3_module_manifest.js");
const RATCHET_PATH = path.join(ROOT, "tests", "test_frontend_size_ratchet.py");
const CENSUS_TOOL = path.join(__dirname, "census.mjs");
const CONVERT_TOOL = path.join(__dirname, "convert_dashboard.mjs");
const CLUSTERS_TOOL = path.join(__dirname, "find_clusters.mjs");
const BRIDGE_MARKER = "// AUTO-GENERATED by tools/js_codemod/convert_dashboard.mjs";
const MANIFEST_ANCHOR = "loaded_by:'dashboard_source_truth_banners.js',";
const RATCHET_RE = /DASHBOARD_JS_MAX_LINES = ([\d_]+)/;

function parseProgram(source) {
  return babelParser.parse(source, { sourceType: "module" }).program;
}

function die(message) {
  console.error("ABORT: " + message);
  process.exit(1);
}

function eolOf(text) {
  return text.includes("\r\n") ? "\r\n" : "\n";
}

// Both files this tool comments into wrap their prose near 76 columns. A
// generated one-liner that blows past that is the kind of thing a reviewer
// reformats by hand every pass, so wrap it here instead.
function wrapComment(text, prefix, eol, width = 76) {
  const lines = [];
  let line = prefix;
  for (const word of text.split(/\s+/)) {
    if (line !== prefix && line.length + 1 + word.length > width) {
      lines.push(line);
      line = prefix + word;
    } else {
      line = line === prefix ? prefix + word : `${line} ${word}`;
    }
  }
  lines.push(line);
  return lines.join(eol);
}

function parseArgs(argv) {
  const out = { module: null, manifestFile: null, check: false };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--module") out.module = argv[++i];
    else if (argv[i] === "--manifest-file") out.manifestFile = argv[++i];
    else if (argv[i] === "--check") out.check = true;
    else die(`unknown argument ${argv[i]}`);
  }
  if (!out.module) die("--module is required");
  return out;
}

// ---------------------------------------------------------------- AST walking

// Dependency-free recursive walk. @babel/traverse is not a dependency of this
// repo and pulling it in for one visitor is not worth the install.
function walk(node, visit) {
  if (!node || typeof node !== "object") return;
  if (Array.isArray(node)) {
    for (const child of node) walk(child, visit);
    return;
  }
  if (typeof node.type !== "string") return;
  visit(node);
  for (const key of Object.keys(node)) {
    if (key === "loc" || key === "leadingComments" || key === "trailingComments") continue;
    walk(node[key], visit);
  }
}

function topLevelBindingNames(source) {
  const names = new Set();
  for (const raw of parseProgram(source).body) {
    const stmt =
      raw.type === "ExportNamedDeclaration" && raw.declaration ? raw.declaration : raw;
    if (stmt.type === "FunctionDeclaration" && stmt.id) names.add(stmt.id.name);
    else if (stmt.type === "VariableDeclaration") {
      for (const d of stmt.declarations) if (d.id.type === "Identifier") names.add(d.id.name);
    }
  }
  return names;
}

// Every identifier the module MENTIONS, minus the obvious non-references
// (`a.b`'s `b`, `{b: 1}`'s `b`). Deliberately over-inclusive: a function
// parameter that happens to share a name with a dashboard.js binding will be
// counted as a reference. That direction is harmless -- it makes the tool
// verify one extra bridge entry that already exists. The opposite direction
// (missing a real reference) is the one that would matter, and this does not
// do that.
function referencedIdentifiers(source) {
  const refs = new Set();
  const skip = new Set();
  walk(parseProgram(source), (node) => {
    if (node.type === "MemberExpression" && !node.computed && node.property) skip.add(node.property);
    if (node.type === "ObjectProperty" && !node.computed && node.key) skip.add(node.key);
    if (node.type === "ObjectMethod" && !node.computed && node.key) skip.add(node.key);
  });
  walk(parseProgram(source), (node) => {
    if (node.type === "Identifier" && !skip.has(node)) refs.add(node.name);
  });
  return refs;
}

// Bare identifiers the module ASSIGNS to. These are the ones that need a set
// accessor on the bridge, not just a get.
function assignedIdentifiers(source) {
  const written = new Set();
  walk(parseProgram(source), (node) => {
    if (node.type === "AssignmentExpression" && node.left && node.left.type === "Identifier") {
      written.add(node.left.name);
    }
    if (node.type === "UpdateExpression" && node.argument && node.argument.type === "Identifier") {
      written.add(node.argument.name);
    }
  });
  return written;
}

// ------------------------------------------------------------- bridge reading

// The generated block at the bottom of dashboard.js, in two shapes:
//   Object.defineProperty(window, "name", { get: ..., set: ..., ... });
//   Object.assign(window, { name, name, ... });
function readBridge(dashboardSource) {
  const idx = dashboardSource.indexOf(BRIDGE_MARKER);
  if (idx === -1) die("dashboard.js has no generated bridge block -- run convert_dashboard.mjs first");
  const block = dashboardSource.slice(idx);
  const accessors = new Map();
  for (const line of block.split(/\r?\n/)) {
    const m = /Object\.defineProperty\(window, "([^"]+)"/.exec(line);
    if (m) accessors.set(m[1], /\bset:/.test(line));
  }
  const valueCopies = new Set();
  const assignStart = block.indexOf("Object.assign(window, {");
  if (assignStart !== -1) {
    const assignBlock = block.slice(assignStart, block.indexOf("});", assignStart));
    for (const m of assignBlock.matchAll(/^\s*([A-Za-z_$][\w$]*),/gm)) valueCopies.add(m[1]);
  }
  return { accessors, valueCopies };
}

// ------------------------------------------------------------------ the steps

function wireIndexHtml(moduleRel) {
  const base = path.basename(moduleRel);
  let html = fs.readFileSync(INDEX_HTML_PATH, "utf8");
  const eol = eolOf(html);

  if (html.includes(`js/${base}?`)) {
    return { changed: false, note: `already wired in index.html (${base})` };
  }

  const dashTagRe = /^([ \t]*)<script type="module" src="js\/dashboard\.js\?v=(\d+)"><\/script>[ \t]*$/m;
  const m = dashTagRe.exec(html);
  if (!m) die("could not find the dashboard.js <script> tag in frontend/index.html");

  const indent = m[1];
  const nextVersion = Number(m[2]) + 1;
  // Immediately BEFORE dashboard.js, where row_model.js already sits. Not
  // after it with the other leaves: dashboard.js ends its module body with a
  // queueMicrotask() whose checkpoint can fire before a LATER module script
  // has evaluated, so a leaf loaded after it is not guaranteed to have
  // installed its window bridge in time.
  const newTag = `${indent}<script type="module" src="js/${base}?v=1"></script>`;
  const bumpedDashTag = `${indent}<script type="module" src="js/dashboard.js?v=${nextVersion}"></script>`;
  html = html.replace(dashTagRe, newTag + eol + bumpedDashTag);
  return {
    changed: true,
    text: html,
    note: `index.html: added ${base} before dashboard.js, bumped dashboard.js ?v=${m[2]} -> ?v=${nextVersion}`,
  };
}

function updateManifest(manifestFile) {
  if (!manifestFile) return { changed: false, note: "manifest: skipped (no --manifest-file given)" };
  const note = fs.readFileSync(path.resolve(ROOT, manifestFile), "utf8");
  const src = fs.readFileSync(MANIFEST_PATH, "utf8");
  const eol = eolOf(src);

  // Idempotence: re-running the tool must not append a second copy of the same
  // note. Match on the note's first line, which by convention starts "vN (...)".
  const firstLine = note.split(/\r?\n/).find((l) => l.trim());
  if (firstLine && src.includes(firstLine.trim())) {
    return { changed: false, note: "manifest: note already present, left alone" };
  }

  const anchorIdx = src.indexOf(MANIFEST_ANCHOR);
  if (anchorIdx === -1) die(`could not find the manifest anchor line (${MANIFEST_ANCHOR})`);
  const lineStart = src.lastIndexOf("\n", anchorIdx) + 1;
  const indent = /^[ \t]*/.exec(src.slice(lineStart))[0];
  // Re-indent and re-comment the note so the caller's file can be plain prose.
  const body = note
    .replace(/\s+$/, "")
    .split(/\r?\n/)
    .map((l) => (l.trim().startsWith("//") ? indent + l.trim() : `${indent}// ${l.trim()}`.trimEnd()))
    .join(eol);
  return {
    changed: true,
    text: src.slice(0, lineStart) + body + eol + src.slice(lineStart),
    note: `manifest: inserted ${note.split(/\r?\n/).length} note line(s) before ${MANIFEST_ANCHOR}`,
  };
}

function updateRatchet(moduleRel, movedCount) {
  const src = fs.readFileSync(RATCHET_PATH, "utf8");
  const eol = eolOf(src);
  const m = RATCHET_RE.exec(src);
  if (!m) die("could not find DASHBOARD_JS_MAX_LINES in tests/test_frontend_size_ratchet.py");

  const previous = Number(m[1].replace(/_/g, ""));
  const actual = fs.readFileSync(DASHBOARD_PATH, "utf8").split(/\r?\n/).length -
    (fs.readFileSync(DASHBOARD_PATH, "utf8").endsWith("\n") ? 1 : 0);

  if (actual > previous) {
    die(
      `the ratchet only moves down. dashboard.js is now ${actual} lines but the ` +
        `ceiling is ${previous}. Something grew the file; investigate rather than raising it.`,
    );
  }
  if (actual === previous) return { changed: false, note: `ratchet: already at ${actual}` };

  const grouped = String(actual).replace(/\B(?=(\d{3})+(?!\d))/g, "_");
  const today = new Date().toISOString().slice(0, 10);
  const comment =
    wrapComment(
      `${today}: lowered from ${previous.toLocaleString("en-US")} -- extracted ` +
        `${movedCount} declaration(s) into ${path.basename(moduleRel)} via ` +
        "tools/js_codemod/extract_module.mjs. Measured after regenerating the " +
        "census and bridge, so it includes the bridge shrinking as those names " +
        "left its Object.assign block.",
      "# ",
      eol,
    ) + eol;

  const lineStart = src.lastIndexOf("\n", src.indexOf(m[0])) + 1;
  const text =
    src.slice(0, lineStart) + comment + `DASHBOARD_JS_MAX_LINES = ${grouped}` +
    src.slice(lineStart + m[0].length);
  return {
    changed: true,
    text,
    note: `ratchet: ${previous.toLocaleString("en-US")} -> ${actual.toLocaleString("en-US")} lines`,
  };
}

function runTool(toolPath, label) {
  try {
    const out = execFileSync(process.execPath, [toolPath], { cwd: ROOT, encoding: "utf8" });
    return out.trim().split(/\r?\n/).pop();
  } catch (err) {
    die(`${label} failed:\n${String(err.stdout || "")}${String(err.stderr || err.message)}`);
  }
}

function nodeSyntaxCheck(filePath) {
  try {
    execFileSync(process.execPath, ["--check", filePath], { stdio: "pipe" });
    return null;
  } catch (err) {
    return String(err.stderr || err.message);
  }
}

// ------------------------------------------------------------ verification

function verify(moduleAbs, moduleRel) {
  const problems = [];
  const dashboard = fs.readFileSync(DASHBOARD_PATH, "utf8");
  const moduleSource = fs.readFileSync(moduleAbs, "utf8");

  for (const [label, file] of [["dashboard.js", DASHBOARD_PATH], [moduleRel, moduleAbs]]) {
    const err = nodeSyntaxCheck(file);
    if (err) problems.push(`${label} is not valid JavaScript:\n${err}`);
  }

  // dashboard.js must never contain the export keyword -- several tests eval()
  // it as a plain non-module script.
  for (const raw of parseProgram(dashboard).body) {
    if (raw.type.startsWith("Export")) {
      problems.push("dashboard.js contains an `export` statement; several tests eval() it as a plain script");
      break;
    }
  }

  const dashTop = topLevelBindingNames(dashboard);
  const moduleTop = topLevelBindingNames(moduleSource);

  const stillInBoth = [...moduleTop].filter((n) => dashTop.has(n));
  if (stillInBoth.length) {
    problems.push(`declared in BOTH dashboard.js and ${moduleRel}: ${stillInBoth.join(", ")}`);
  }

  // The check that nothing else performs: every dashboard.js binding this
  // module reaches back for must be on the bridge, and every one it ASSIGNS to
  // must have a set accessor (module code is strict; a bare assignment to an
  // identifier with no resolvable binding throws at call time).
  const { accessors, valueCopies } = readBridge(dashboard);
  const refs = referencedIdentifiers(moduleSource);
  const writes = assignedIdentifiers(moduleSource);
  const needed = [...refs].filter((n) => dashTop.has(n) && !moduleTop.has(n)).sort();

  const unbridged = needed.filter((n) => !accessors.has(n) && !valueCopies.has(n));
  if (unbridged.length) {
    problems.push(
      `${moduleRel} references dashboard.js binding(s) that the bridge does not expose: ` +
        `${unbridged.join(", ")}. Re-run census.mjs then convert_dashboard.mjs.`,
    );
  }

  const writtenNeedingSetter = needed.filter((n) => writes.has(n));
  const missingSetter = writtenNeedingSetter.filter((n) => !accessors.get(n));
  if (missingSetter.length) {
    problems.push(
      `${moduleRel} assigns to dashboard.js binding(s) with no set accessor on the bridge: ` +
        `${missingSetter.join(", ")}. Those assignments will throw a ReferenceError at call ` +
        "time (module code is strict). If the binding is `const` in dashboard.js it cannot " +
        "be written at all and the module logic needs rethinking.",
    );
  }

  return { problems, needed, writtenNeedingSetter };
}

// ------------------------------------------------------------------- driver

function main() {
  const args = parseArgs(process.argv);
  const moduleRel = args.module.replace(/\\/g, "/");
  const moduleAbs = path.resolve(ROOT, moduleRel);

  if (!fs.existsSync(moduleAbs)) {
    die(`${moduleRel} does not exist. Run extract_module.mjs first -- census.mjs only picks up the new module's cross-file references once the file is on disk.`);
  }
  const movedCount = topLevelBindingNames(fs.readFileSync(moduleAbs, "utf8")).size;

  // Snapshot everything this tool may write, so any failure restores the tree
  // rather than leaving a half-applied follow-up. Same hard-abort philosophy
  // as extract_module.mjs.
  const touched = [
    INDEX_HTML_PATH, DASHBOARD_PATH, MANIFEST_PATH, RATCHET_PATH,
    path.join(__dirname, "census_report.json"),
    path.join(__dirname, "clusters_report.json"),
  ];
  const snapshot = new Map(
    touched.filter((p) => fs.existsSync(p)).map((p) => [p, fs.readFileSync(p, "utf8")]),
  );
  const rollback = (message) => {
    for (const [p, text] of snapshot) fs.writeFileSync(p, text, "utf8");
    die(message + "\n(all files restored)");
  };

  const notes = [];

  const html = wireIndexHtml(moduleRel);
  notes.push(html.note);

  if (args.check) {
    console.log(`CHECK: ${moduleRel}, ${movedCount} top-level declaration(s).`);
    for (const n of notes) console.log("  - " + n);
    console.log("  - would run: census.mjs, convert_dashboard.mjs, find_clusters.mjs");
    console.log("  - would update the manifest and the size ratchet");
    console.log("Nothing was written. Re-run without --check to apply.");
    return;
  }

  if (html.changed) fs.writeFileSync(INDEX_HTML_PATH, html.text, "utf8");

  // Order matters: census reads frontend/js/*.js to find cross-file
  // references, and convert_dashboard reads the census to decide which
  // bindings need accessors. Reversing them regenerates the bridge from stale
  // data.
  notes.push("census: " + runTool(CENSUS_TOOL, "census.mjs"));
  notes.push("convert: " + runTool(CONVERT_TOOL, "convert_dashboard.mjs"));
  notes.push("clusters: " + runTool(CLUSTERS_TOOL, "find_clusters.mjs"));

  const manifest = updateManifest(args.manifestFile);
  if (manifest.changed) fs.writeFileSync(MANIFEST_PATH, manifest.text, "utf8");
  notes.push(manifest.note);

  // After convert_dashboard, because regenerating the bridge changes the line
  // count and the ratchet must record the final number.
  const ratchet = updateRatchet(moduleRel, movedCount);
  if (ratchet.changed) fs.writeFileSync(RATCHET_PATH, ratchet.text, "utf8");
  notes.push(ratchet.note);

  const { problems, needed, writtenNeedingSetter } = verify(moduleAbs, moduleRel);
  if (problems.length) {
    rollback("verification FAILED:\n  - " + problems.join("\n  - "));
  }

  console.log(`FINISHED ${moduleRel} (${movedCount} declaration(s))`);
  for (const n of notes) console.log("  - " + n);
  console.log(
    `\nBridge surface verified: ${needed.length} dashboard.js binding(s) reached through ` +
      `window, ${writtenNeedingSetter.length} of them written and all with set accessors.`,
  );
  if (needed.length) console.log("  " + needed.join(", "));

  console.log("\nStill manual (these need judgement, not automation):");
  console.log("  1. Fix tests that assert against dashboard.js source text. Run the FULL");
  console.log("     suite once now -- a targeted grep misses cases and costs extra cycles.");
  console.log("     The fix is usually to switch the file to");
  console.log("     tests/_decomp_dashboard.py's dashboard_js_text(), which globs every");
  console.log("     dashboard_decomp_*.js, instead of reading dashboard.js alone.");
  console.log("  2. If that removes a file's last raw read_text of a frontend asset, drop it");
  console.log("     from tests/fixtures/frontend_source_grep_baseline.json (the freeze test");
  console.log("     requires retired entries to be removed).");
  console.log("  3. Review the generated manifest and ratchet comments; expand the prose if");
  console.log("     this pass had anything non-obvious about it.");
  console.log("  4. Browser smoke: load the app, exercise the moved UI, confirm no");
  console.log("     ReferenceError. NOTE: the app writes to the MAIN repo's");
  console.log("     local_state/*.db even when served from a worktree.");
}

main();
