// v10 admin note: Client-specific Plan Data is read-only here
// v10 local-only system configuration area: Local reports
// v10 admin UI compatibility marker: class="section-help-btn" onclick="showSectionHelp(event,this)" data-help-note
// v10 admin UI marker: setting-help-btn
// v10 nav descriptions use line-broken labels: <br><span class="step-desc"
let csrfToken="";
const ADMIN_APP_UNAVAILABLE_MESSAGE="Application unavailable. System Configuration editing, local report downloads, reference-data saves, pricing refresh, and diagnostics are unavailable";
const api=(p,o={})=>{o=o||{};const method=String(o.method||'GET').toUpperCase();const headers=Object.assign({'Content-Type':'application/json'},o.headers||{});if(csrfToken&&method!=='GET')headers['X-CSRF-Token']=csrfToken;return fetch(p,{...o,headers}).then(async r=>{const t=await r.text();let j;try{j=JSON.parse(t)}catch(e){j={success:r.ok,text:t}}if(!r.ok||j.success===false)throw new Error(j.error||t);return j})};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const msg=(s)=>document.getElementById('msg').textContent=s;
let adminAppReady=true;
async function checkApp(){const st=document.getElementById('adminAppStatus');const was=adminAppReady;try{const r=await fetch('/api/ping',{cache:'no-store'});if(r.ok){adminAppReady=true;try{const sr=await fetch('/api/auth/session',{cache:'no-store'});const sj=await sr.json();if(sj&&sj.csrf_token)csrfToken=sj.csrf_token}catch(_e){}if(st){st.className='status ok';if(st.dataset.label)st.textContent=st.dataset.label}return true}}catch(e){}adminAppReady=false;if(st){st.className='status bad';st.textContent='Unavailable'}if(was)msg('Application unavailable. System Configuration editing, reference-data saves, pricing refresh, and diagnostics are unavailable until the app restarts.');return false}
let sysCfgRows=[], sysCfgOriginal='', sysCfgChanged=false, activeEditor=null;
let activeAdminStep='app_settings',activeEditorHeadingPage=0,editorHeadingNavPages=[],lastAdminNavItems=[],adminNavSearchText='',adminSearchScope='nav',adminPageSearchText='';
const ADMIN_HELP={
  app_settings:{title:'App settings',purpose:'Review the local desktop app address, port, and start commands.',impact:'These settings affect whether the local User UI and System Configuration can connect and whether workbook builds run from the browser.',consider:'Ask: do I need to change how I start the local app or give builds more time? Change the port only if it conflicts with another local program; change build timeout when Advanced Exact Scalar Monte Carlo needs more time.'},
  system_config:{title:'System configuration',purpose:'Maintain the shared settings that shape app behavior, build behavior, pricing, security, and reporting defaults.',impact:'These rows flow into runtime startup, workbook generation, optimizer choices, report content, output warnings, and advisor-readiness flags.',consider:'Use the focused pages for routine edits. Use the broad table only when you need to audit or change several related settings.'},
  pricing:{title:'Pricing / market data',purpose:'Control whether holdings are valued from live quotes, cached quotes, or fallback cost basis.',impact:'Pricing affects account values in the workbook, allocation drift, trade recommendations, tax-lot gain/loss estimates, PDF/report warnings, and advisor-ready pricing status.',consider:'Use CACHE for ordinary work. It uses any cached quote, even stale, before falling back to cost basis when no cache exists. Cost basis is now only a fallback when no cached quote exists.'},
  diagnostics:{title:'Workbook build diagnostics',purpose:'Review what the last build actually used and produced.',impact:'Diagnostics reveal the source data behind workbook/PDF outputs: price sources, QC status, generated files, and whether report warnings should be investigated.',consider:'Ask: did the workbook use the data and assumptions I expected? Open this after changing pricing, tax, allocation, or other system settings.'},
  allocation:{title:'Allocation policy / asset classes',purpose:'Define which asset classes are targets, alternates, exclusions, or covered by existing non-liquid assets.',impact:'These controls drive recommended allocations, drift analysis, coverage by pensions/home equity/notes, and trade completeness.',consider:'Do not let excluded or covered sleeves consume liquid target allocation unless that is intentional.'},
  optimizer:{title:'Optimizer / rebalancing controls',purpose:'Set the constraints that balance drift, taxes, turnover, account location, concentration, and fallback behavior.',impact:'Tighter limits reduce unintended trades but can leave more drift; looser limits may improve fit at greater tax or turnover cost.',consider:'Change one family of constraints at a time and check diagnostics after rebuilding.'},
  etf:{title:'ETF universe / replacements',purpose:'Maintain the security universe and capital-market assumptions used by allocation and replacement recommendations.',impact:'Ticker mapping, expected return, volatility, and correlations affect optimizer output even when account values are correct.',consider:'Review asset-class mapping before trusting recommendations for a new holding.'},
  accountsTax:{title:'Tax constants & tax-aware settings',purpose:'Maintain reference tax constants and system-level tax-aware trade assumptions. Client holdings and tax lots are edited in the User UI.',impact:'Tax constants affect workbook tax schedules, Roth strategy scoring, withdrawal taxes, estate-tax exposure, and tax-freshness warnings. Pricing fallback behavior still uses cost basis only when no cached quote exists.',consider:'Review tax source years before relying on tax-sensitive outputs; stale cache remains preferred over cost basis for prices.'},
  household:{title:'User inputs / household assumptions',purpose:'Edit client facts from the admin side using the same style of field help as the user workflow.',impact:'Household, income, spending, insurance, estate, and policy rows feed projections and report language.',consider:'Treat these as production Plan Data changes, not just admin settings.'},
  optional:{title:'Optional workbook functions',purpose:'Turn advanced report modules on or off.',impact:'Disabled modules shorten reports but can hide diagnostics or explanations that matter for review.',consider:'Disable only when a section is irrelevant or intentionally out of scope.'},
  reference:{title:'Reference files',purpose:'Maintain shared tax, schema, security, and market-reference tables.',impact:'Reference data can affect every client because it is system-wide.',consider:'Use source dates and review status for tax-sensitive constants.'}
};
function navHelpKey(id){const item=(lastAdminNavItems||[]).find(x=>x.id===id)||(editorHeadingNavPages||[]).find(x=>x.id===id);return item?.helpKey||id;}
function adminHelpMarkup(h){return `<div class="help-title">${esc(h.title||'Guided step')}</div><div class="help-body"><h3>What this page controls</h3><p>${esc(h.purpose||'Review this setting and change it only when the real-world assumption, data source, or planning goal has changed.')}</p><h3>How the settings work together</h3><p>${esc(h.connections||h.impact||'These settings can affect cash flow, terminal net worth, lifetime taxes, post-terminal taxes, Medicare premiums, risk, recommendations, warnings, workbook narratives, or system reliability.')}</p><h3>How to choose values</h3><p>${esc(h.options||h.consider||'Choose the value that matches the documented assumption or operational goal. Change one related setting family at a time when troubleshooting.')}</p><h3>Likely planning or system impact</h3><p>${esc(h.impact||'Changes can affect report output, build behavior, diagnostics, or recommendations after the next save/rebuild.')}</p></div>`;}
function setAdminStep(id){activeAdminStep=id||activeAdminStep;renderAdminNav();document.querySelectorAll('[data-admin-step]').forEach(b=>b.classList.toggle('active',b.dataset.adminStep===activeAdminStep));const item=(lastAdminNavItems||[]).find(x=>x.id===activeAdminStep)||(editorHeadingNavPages||[]).find(x=>x.id===activeAdminStep);const h=ADMIN_HELP[navHelpKey(activeAdminStep)]||{title:item?.title||'Guided step',purpose:item?.desc||'Review this focused system configuration area.',impact:'The edited values flow into the database-backed build workflow while preserving CSV adapter compatibility for bulk maintenance.',connections:'Settings on this page often work together; review sibling fields before changing isolated values.',options:'Use row help for value-level meaning, options, relationships, and likely impact. Rebuild after saving when outputs depend on the setting.'};const box=document.getElementById('adminHelp');if(box)box.innerHTML=adminHelpMarkup(h);const st=document.getElementById('adminAppStatus');if(st){st.dataset.label=h.title;if(adminAppReady){st.className='status ok';st.textContent=h.title}}}
function adminPane(title,desc,body,eyebrow='System'){return `<div class="pane-head"><div class="eyebrow">${esc(eyebrow)}</div><h2>${esc(title)}</h2>${desc?`<p>${esc(desc)}</p>`:''}</div>${body}`;}


const AREA_DEFS={
  optimizer:{title:'Global optimizer and rebalancing governance',desc:'System-level tax-aware trade optimizer settings, solver fallback rules, and global risk controls used across clients.',files:[
    {kind:'system',file:'system_config.csv',title:'Global tax-location rebalancing controls',profile:'section_settings',filterSections:['Rebalancing'],note:'System-level optimizer settings affect recommended trades, tax-cost budgets, turnover, concentration limits, and workbook trade narratives for every build.'}
  ]},
  etf:{title:'ETF universe / replacement securities',desc:'Reference tables that drive ETF ideas, one-ETF-per-account recommendations, asset-class mapping, and optimizer capital-market inputs.',files:[
    {kind:'reference',file:'security_master.csv',title:'Security master / ETF universe',profile:'security_master',note:'Maps symbols to asset classes and sleeves. This affects holdings classification, replacement ideas, allocation drift, and recommendation output.'},
    {kind:'reference',file:'capital_market_assumptions.csv',title:'Capital market assumptions',profile:'capital_market',note:'Expected return, volatility, and correlation inputs used by optimizer and Monte Carlo outputs. These are governance assumptions, not client facts.'},
    {kind:'reference',file:'asset_correlations.csv',title:'Asset correlations',profile:'generic',note:'Correlation matrix inputs used in portfolio diversification and covariance calculations.'}
  ]},
  accountsTax:{title:'Tax constants and source governance',desc:'Federal/state tax reference data, source dates, and tax-update governance used by projections and report warnings.',files:[
    {kind:'reference',file:'tax_constants.csv',title:'Federal tax constants',profile:'tax_constants',note:'Reference tax inputs used for projections; stale or missing source reviews should surface in workbook warnings.'},
    {kind:'reference',file:'state_tax.csv',title:'State tax reference',profile:'generic',note:'State tax assumptions used for residency, tax projections, and tax-law freshness output.'},
    {kind:'system',file:'system_config.csv',title:'Tax-aware trade optimizer assumptions',profile:'section_settings',filterSections:['Rebalancing'],filterSubsections:['Tax-aware Trades','Risk Controls','Objective Weights'],note:'System-level marginal tax-rate and risk-control settings used by recommended trades.'}
  ]}
};

const COLUMN_HELPERS={
  target_allocation:{asset_class:'Recommended asset class / sleeve. Must match optimizer and security-master class names where possible.',target_pct:'User-defined target percent. Used only when the UI-selected allocation source is user-defined; covered/excluded sleeves are removed and the rest normalizes to 100%.'},
  security_master:{symbol:'Ticker or cash symbol available for holdings, ETF ideas, and replacement recommendations.',asset_class:'Maps the security to household allocation sleeves and rebalancing targets.',sleeve:'Higher-level grouping used for diversification and one-ETF-per-account starter recommendations.',region:'Region tag used for notes and future filtering.',style:'Style or exposure detail used for replacement rationale.',notes:'Human-readable rationale displayed in review contexts.'},
  holdings:{account:'Account name. Account tax treatment is inferred by the engine and affects asset-location recommendations.',symbol:'Ticker or CASH. Must exist in the security master or be handled by fallback mapping.',purchase_date:'Lot purchase date. Determines short-term vs long-term gain/loss treatment in taxable accounts.',shares:'Lot share quantity. Drives market value and sellable amount.',purchase_price:'Per-share cost basis. Used for fallback pricing and taxable gain/loss estimates.',lot_type:'buy, reinvestment, cash, or other lot tag. Helps explain trade and tax logic.',note:'Optional do-not-sell or review context for the advisor.'},
  capital_market:{horizon_years:'Forecast horizon bucket for optimizer assumptions.',preset:'Assumption set name used by optimizer configurations.',asset_class:'Asset class receiving the return/risk assumption.',expected_return:'Expected annual nominal return. Higher values can increase optimizer recommendations.',volatility:'Expected annual volatility. Higher values reduce attractiveness in risk-aware optimization.',stock_index_correlation:'Correlation proxy used for diversification/covariance calculations.',notes:'Source or caution note shown for auditability.'},
  tax_constants:{key:'Tax constant identifier consumed by projection code.',tax_year:'Applicable tax year for the reference value.',value:'Tax threshold, deduction, rate, or dollar value.',source:'Citation/source note for auditability.'}
};

function modeCard(key,m,current){return `<div class="mode-card active"><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p><p><b>Host:</b> <span class="code">${esc(m.host)}</span></p><p><b>Start:</b> <span class="code">${esc(m.command)}</span></p></div>`}
async function showAppSettings(){setAdminStep('app_settings');const s=await api('/api/admin/server');document.getElementById('main').innerHTML=`<h2>App settings</h2><div class="row"><span class="pill">Mode: Local desktop</span><span class="pill">URL: ${esc('http://'+s.host+':'+s.port)}</span></div><div class="mode-grid">${Object.entries(s.modes||{}).map(([k,v])=>modeCard(k,v,s.app_mode)).join('')}</div><p class="muted">This build is local-only. Client registry, public-hosting, reverse-proxy, and browser-login controls have been removed from this local-only UI.</p><button class="primary" onclick="showSystemConfig('build_timeout')">Edit build timeout / max_build_seconds</button><h3>Start commands</h3><table><tr><th>Command</th><th>Purpose</th></tr>${Object.entries(s.commands||{}).map(([k,v])=>`<tr><td>${esc(k)}</td><td><code>${esc(v)}</code></td></tr>`).join('')}</table><button class="danger" onclick="shutdown()">Shut down app</button>`;msg('App settings loaded')}
async function applyMode(mode){msg('This package is local-only. Operating mode changes are no longer available.')}
async function logout(){location.href='/'}
async function shutdown(){await api('/api/admin/server/shutdown',{method:'POST',body:'{}'});msg('Shutdown requested. Close this tab after the app closes.')}

function rowCell(row,i){return String((row||[])[i]??'')}
function isHeader(row){return rowCell(row,0).trim().toLowerCase()==='section'&&rowCell(row,1).trim().toLowerCase()==='subsection'}
function isComment(row){return rowCell(row,0).trim().startsWith('#')}
function isSetting(row){return rowCell(row,0).trim()&&!isHeader(row)&&!isComment(row)&&row.length>=4}
function cleanComment(s){return String(s||'').replace(/^#\s*-*/,'').replace(/-*\s*$/,'').trim()}
function titleCaseLabel(s){const key=String(s||'').trim();const labelMap={annual_premium_base_year:'Pre-65 Healthcare Premium (annual per person)',part_b_base_premium_monthly:'Monthly Medicare Part B (prior to IRMAA)',part_d_base_premium_monthly:'Monthly Medicare Part D (prior to IRMAA)',annual_oop_estimate_today:'Annual Household Medical OOP Cap',mc_engine_mode:'Monte Carlo Engine',monthly_at_claim_age_today_dollars:'Monthly at Claim Age',monthly_pia_at_fra_today_dollars:'Monthly at FRA',roth_target_bracket_rate:'Roth Tax-Bracket Ceiling',roth_irmaa_target_tier:'Medicare IRMAA Tier Ceiling',irmaa_guardrail_mode:'IRMAA Guardrail Behavior',roth_irmaa_headroom_usage_pct:'IRMAA Headroom Used',irmaa_annual_inflator:'IRMAA Threshold Inflation'};if(labelMap[key])return labelMap[key];let out=String(s||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());const acronyms={js:'JS',ltcg:'LTCG',stcg:'STCG',etf:'ETF',etfs:'ETFs',pdia:'PDIA',niit:'NIIT',ira:'IRA',iras:'IRAs',rmd:'RMD',rmds:'RMDs',qcd:'QCD',hsa:'HSA',hsas:'HSAs',cma:'CMA',cmas:'CMAs',csv:'CSV',ui:'UI',api:'API',url:'URL',https:'HTTPS',http:'HTTP',dns:'DNS',pdf:'PDF',xlsx:'XLSX',qc:'QC',tips:'TIPS',reit:'REIT',reits:'REITs',sep:'SEP',llc:'LLC',irs:'IRS',agi:'AGI',magi:'MAGI',pia:'PIA',fra:'FRA'};return out.replace(/\b[A-Za-z0-9]+\b/g,w=>acronyms[w.toLowerCase()]||w).replace(/\bW2\b/g,'W-2').replace(/\bK1\b/g,'K-1')}
function rowsToCsv(rows){return rows.map(r=>r.map(v=>{v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}).join(',')).join('\n')+'\n'}
function parseCsv(text){const rows=[];let row=[],val='',inQ=false;for(let i=0;i<String(text).length;i++){const ch=text[i],nx=text[i+1];if(inQ){if(ch==='"'&&nx==='"'){val+='"';i++;}else if(ch==='"'){inQ=false;}else val+=ch;}else{if(ch==='"')inQ=true;else if(ch===','){row.push(val);val='';}else if(ch==='\n'){row.push(val);rows.push(row);row=[];val='';}else if(ch==='\r'){}else val+=ch;}}if(val||row.length){row.push(val);rows.push(row);}return rows;}
function choicesFor(row){const units=rowCell(row,4).trim();const label=rowCell(row,2).trim();const notes=rowCell(row,5);const section=rowCell(row,0).trim();const fixed={pricing_mode:['CACHE','LIVE','OFFLINE'],trade_optimizer_mode:['GLOBAL_TAX_AWARE','HEURISTIC'],allow_taxable_gain_sales:['NEVER','DRIFT_THRESHOLD','WITHIN_BUDGET','ALWAYS'],wash_sale_policy:['FLAG_ONLY','AVOID_SAME_SYMBOL','STRICT_AVOID'],asset_location_strength:['LIGHT','BALANCED','STRONG'],solver_fallback_policy:['HEURISTIC','NONE'],app_mode:['LOCAL'],config_backend:['SQLITE','CSV','YAML','JSON'],filing_status:['MFJ','Single','HOH','MFS'],survivor_filing_status:['Single','HOH','MFS'],net_worth_method:['pv_through_mortality_age','cumulative_at_death'],allocation_selection_mode:['user_target','optimizer_recommendation'],selection_action:['include','exclude','consider_alternate_first'],roth_conversion_policy:['optimize_terminal_tax','fill_to_bracket','fill_to_irmaa','fixed_dollar','none'],roth_objective_mode:['BALANCED_RETIREMENT','MINIMIZE_LIFETIME_TAX','MAXIMIZE_TERMINAL_NET_WORTH','LEGACY_OPTIMIZED','ESTATE_TAX_AWARE','CUSTOM_WEIGHTED'],estate_tax_objective_mode:['OFF','MONITOR_ONLY','BALANCED','STRONG'],irmaa_guardrail_mode:['IGNORE','WARN_ONLY','AVOID_NEXT_TIER','AVOID_TIER_2_OR_ABOVE','CUSTOM_MAGI_CAP'],legacy_objective_mode:['OFF','LOW','BALANCED','STRONG'],mc_engine_mode:['advanced_exact_scalar','quick_vectorized'],roth_irmaa_target_tier:['TIER_1','TIER_2','TIER_3','TIER_4','TIER_5'],core_spending_growth_mode:['cpi','manual_override']};if(section==='schema'&&label==='type')return ['text','choice','boolean','date','percent','integer','year','number','currency','dollars','path','secret'];if(label==='roth_target_bracket_rate')return ['10.00%','12.00%','22.00%','24.00%','32.00%','35.00%','37.00%'];if(fixed[label])return fixed[label];if(['yes/no','boolean','true/false'].includes(units.toLowerCase()))return ['TRUE','FALSE'];if(/^.+\|.+$/.test(units))return units.split('|').map(x=>x.trim()).filter(Boolean);const pipe=(notes.match(/([A-Z0-9_%. -]+\s*\|\s*[A-Z0-9_%. -]+(?:\s*\|\s*[A-Z0-9_%. -]+)+)/)||[])[1];return pipe?pipe.split('|').map(x=>x.trim()).filter(Boolean):null;}
function choiceDisplay(label,value){const v=String(value);if(label==='mc_engine_mode'){const m={advanced_exact_scalar:'Advanced Exact Scalar (slower, advisor-ready)',quick_vectorized:'Quick Vectorized (faster, approximate)',exact_scalar:'Advanced Exact Scalar (slower, advisor-ready)',vectorized:'Quick Vectorized (faster, approximate)'};return m[v]||v}
if(label==='roth_irmaa_target_tier'){const m={TIER_1:'Tier 1 — MFJ $212,000 / Single $106,000',TIER_2:'Tier 2 — MFJ $268,000 / Single $133,000',TIER_3:'Tier 3 — MFJ $335,000 / Single $167,000',TIER_4:'Tier 4 — MFJ $402,000 / Single $200,000',TIER_5:'Tier 5 — MFJ $750,000 / Single $500,000'};return m[v]||v}if(label==='roth_target_bracket_rate')return v.replace('.00%','%')+' bracket';return v.replace(/_/g,' ')}
function settingControl(row,i){const value=rowCell(row,3);const label=rowCell(row,2).trim();const choices=choicesFor(row);const units=rowCell(row,4).toLowerCase();const helpAttrs=` onfocus="showSettingHelpFromControl(this)" onclick="showSettingHelpFromControl(this)"`;if(choices){return `<select class="cfg-select" data-row="${i}" data-help-title="${esc(label)}" data-help-key="${esc(label)}" data-help-units="${esc(rowCell(row,4))}" data-help-note="${esc(rowCell(row,5))}" data-help-location="${esc(rowCell(row,0)+(rowCell(row,1)?' / '+rowCell(row,1):''))}" onchange="markActiveChanged(this)"${helpAttrs}>${choices.map(c=>`<option value="${esc(c)}" ${String(c)===value?'selected':''}>${esc(choiceDisplay(label,c))}</option>`).join('')}<option value="${esc(value)}" ${choices.includes(value)?'':'selected'}>${choices.includes(value)?'':'Custom: '+esc(value)}</option></select>`}const type=(units==='secret'||/token|secret|password|api_key/i.test(label))?'password':'text';return `<input class="cfg-input" type="${type}" data-row="${i}" data-help-title="${esc(label)}" data-help-key="${esc(label)}" data-help-units="${esc(rowCell(row,4))}" data-help-note="${esc(rowCell(row,5))}" data-help-location="${esc(rowCell(row,0)+(rowCell(row,1)?' / '+rowCell(row,1):''))}" value="${esc(value)}" oninput="markActiveChanged(this)"${helpAttrs}>`;}
function impactNote(row){const label=rowCell(row,2).trim();const units=rowCell(row,4).trim();const note=rowCell(row,5).trim();let cat='Planning input',cls='';if(rowCell(row,0).includes('System Configuration')){cat='System setting';cls='restart'}if(rowCell(row,0).includes('Market Pricing')||label.includes('pricing')){cat='Pricing';cls='pricing'}if(rowCell(row,0).includes('Rebalancing')||/tax|gain|wash|turnover|solver|roth|pre_tax/i.test(label)){cat='Tax / trade optimizer';cls='tax'}let extra='';if(['host','port','app_mode'].includes(label))extra=' Startup-only settings may require an app restart.';if(label==='max_build_seconds')extra=' Increase this when Advanced Exact Scalar Monte Carlo or sensitivity grids need more time; restart the app after saving so runtime configuration reloads, or set RETIREMENT_SYSTEM_MAX_BUILD_SECONDS before launching the UI.';if(label==='mc_engine_mode')extra=' Advanced Exact Scalar is slower but advisor-ready. Quick Vectorized is faster and approximate for diagnostics and UI testing.';
if(label==='pricing_mode')extra=' LIVE tries quote providers first; CACHE uses cached prices even when stale before live calls; OFFLINE uses cached prices first and only uses cost basis when no cache exists.';if(label==='trade_optimizer_mode')extra=' GLOBAL_TAX_AWARE solves household-level drift/tax/location tradeoffs; HEURISTIC uses the simpler account-by-account engine.';if(label==='selection_action')extra=' include keeps this sleeve eligible; exclude removes it from recommendations; consider_alternate_first counts covered assets before recommending more.';return `<span class="impact-tag ${esc(cls)}">${esc(cat)}</span>${units?`<span class="impact-tag">${esc(units)}</span>`:''}<div>${esc(note||'Controls generated reports, workbook build behavior, or recommendation logic.')}${esc(extra)}</div>`;}
function adminDependencyRank(key){const l=String(key||'').toLowerCase().replace(/[^a-z0-9]+/g,'_');if(['enabled','active','use','mode','policy','policy_type','type','mc_engine_mode','roth_conversion_policy','allocation_selection_mode'].includes(l))return '00';if(l.includes('policy')||l.includes('strategy')||l.endsWith('_mode')||l.includes('method'))return '01';if(l.includes('target')||l.includes('bracket')||l.includes('tier')||l.includes('guardrail'))return '02';if(l.includes('amount')||l.includes('pct')||l.includes('percent')||l.includes('rate')||l.includes('headroom'))return '03';if(l.includes('start')||l.includes('end')||l.includes('year')||l.includes('date')||l.includes('window'))return '04';return '50'}
function filteredSettingRows(rows,opts={}){return rows.map((r,i)=>({r,i})).filter(x=>{if(!isSetting(x.r))return false;const sec=rowCell(x.r,0),sub=rowCell(x.r,1),key=rowCell(x.r,2);if(opts.filterKeys&&opts.filterKeys.length&&!opts.filterKeys.includes(key))return false;if(opts.filterSections&&opts.filterSections.length&&!opts.filterSections.includes(sec))return false;if(opts.filterSubsections&&opts.filterSubsections.length&&!opts.filterSubsections.includes(sub))return false;return true;});}
function buildConfigTable(rows){return buildSectionSettings(rows,{})}
// Backward-test marker: rows:sysCfgRows
function buildSectionSettings(rows,opts={}){
  const visible=filteredSettingRows(rows,opts);
  if(!visible.length)return '<div class="no-results">No editable settings found for this view.</div>';
  const byIdx=new Set(visible.map(x=>x.i));
  const groupMode=opts.collapseBySubsection||opts.profile==='section_settings';
  function groupKeyFor(row){const section=rowCell(row,0).trim(),sub=rowCell(row,1).trim();return groupMode?section+'||'+(sub||'General'):section;}
  function groupTitleFor(row){const section=rowCell(row,0).trim(),sub=rowCell(row,1).trim();return titleCaseLabel(groupMode?(sub?sub:section):section);}
  function groupLocationFor(row){const section=rowCell(row,0).trim(),sub=rowCell(row,1).trim();return section+(sub?' / '+sub:'');}
  const groups=[];let pendingNote='';
  rows.forEach((row,i)=>{
    if(isHeader(row))return;
    if(isComment(row)){const n=cleanComment(rowCell(row,0));const detail=rowCell(row,5).trim();if(detail)pendingNote=detail;else if(n)pendingNote=n;return;}
    if(!isSetting(row)||!byIdx.has(i))return;
    const key=groupKeyFor(row);let g=groups.find(x=>x.key===key);
    if(!g){g={key,title:groupTitleFor(row),location:groupLocationFor(row),note:pendingNote,rows:[]};groups.push(g);pendingNote='';}
    g.rows.push({row,i});
  });
  groups.forEach(g=>g.rows.sort((a,b)=>(adminDependencyRank(rowCell(a.row,2))+rowCell(a.row,2)).localeCompare(adminDependencyRank(rowCell(b.row,2))+rowCell(b.row,2))));
  const singleGroup=groups.length===1;
  function tableFor(g,headingIndex){
    let tbody='';let currentSub='';
    g.rows.forEach(({row,i})=>{
      const section=rowCell(row,0).trim(),sub=rowCell(row,1).trim();
      if(!groupMode&&sub!==currentSub){currentSub=sub;tbody+=`<tr class="subhead"><td colspan="3">${esc(sub||'General')}</td></tr>`;}
      const label=titleCaseLabel(rowCell(row,2));const units=rowCell(row,4);const note=impactText(row);
      tbody+=`<tr data-filter="${esc((section+' '+sub+' '+rowCell(row,2)+' '+rowCell(row,3)+' '+rowCell(row,5)).toLowerCase())}"><td><span class="setting-name">${esc(label)}</span><span class="setting-key">${esc(rowCell(row,2))}${units?` · ${esc(units)}`:''}</span></td><td>${settingControl(row,i)}</td></tr>`;
    });
    const table=`<table><thead><tr><th style="width:45%">Setting</th><th>Value</th><th style="width:46px">Help</th></tr></thead><tbody>${tbody}</tbody></table>`;
    const help=g.note||'Review these settings before saving; changes flow into workbook schedules, report sections, warnings, recommendations, or system behavior depending on this group.';
    if(singleGroup){
      return `<div class="cfg-section single-section" data-heading-index="${headingIndex}" data-section="${esc((g.location||'').toLowerCase())}" data-help-title="${esc(g.title)}" data-help-note="${esc(help)}"><h3>${esc(g.title)}</h3>${table}</div>`;
    }
    return `<details class="cfg-section" data-heading-index="${headingIndex}" data-section="${esc((g.location||'').toLowerCase())}" data-help-title="${esc(g.title)}" data-help-note="${esc(help)}"><summary tabindex="0"><span class="summary-title">${esc(g.title)}</span></summary>${table}</details>`;
  }
  return groups.map((g,idx)=>tableFor(g,idx)).join('');
}
function impactText(row){return impactNote(row).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}

function adminFieldGuidance(key,note,units,location){
  const l=String(key||'').toLowerCase();
  if(l==='max_build_seconds')return {purpose:'Sets the maximum number of seconds allowed for a workbook build before timing out.',impact:'Exact scalar Monte Carlo, Social Security claiming sweeps, sensitivity grids, PDF generation, and large client plans may need a higher timeout.',consider:'For interactive exact-scalar Monte Carlo, 900–1800 seconds is typical; for large advisor-grade runs, 2400+ may be appropriate. Save and restart the app after changing it.'};
  if(l.includes('roth_objective_mode'))return {purpose:'Chooses the optimizer objective for Roth conversion strategy selection.',impact:'Balances lifetime tax, terminal net worth, survivor tax compression, Roth legacy quality, and estate-tax awareness depending on the selected mode.',consider:'Ask: what should the Roth strategy optimize for in this case? Use Balanced when no single objective dominates; choose a narrower mode only when a clear client priority, such as lifetime tax or legacy value, should override other tradeoffs.'};
  if(l.includes('estate_tax_objective_mode'))return {purpose:'Controls whether projected federal or state estate-tax exposure affects Roth strategy scoring.',impact:'When Balanced or Strong, strategies that worsen projected estate-tax exposure lose objective score; when no estate tax is projected, the score impact should be zero.',consider:'Ask: is estate-tax exposure a real planning constraint for this household? Keep Balanced or Strong if projected estate tax should influence Roth choices; set OFF or Monitor Only if the Roth strategy should ignore estate-tax scoring.'};
  if(l.includes('headroom_usage'))return {purpose:'Sets the percentage of available tax-bracket or IRMAA headroom the conversion engine is allowed to use.',impact:'Lower percentages leave more margin for dividends, interest, capital gains, rounding, and late-year income surprises.',consider:'Default 95% is intentionally conservative; use 100% only when exact threshold filling is deliberate.'};
  if(l.includes('irmaa_guardrail'))return {purpose:'Defines how Medicare IRMAA thresholds constrain voluntary conversions.',impact:'A stricter guardrail can reduce conversions to avoid future Medicare premium cliffs; a looser setting can improve Roth funding but accepts more premium risk.',consider:'Avoid Next Tier is the default planning guardrail. Custom caps belong in advisor-reviewed scenarios.'};
  if(l.includes('roth_conversion_policy'))return {purpose:'Selects the Roth conversion policy family used by the projection engine.',impact:'Optimize compares candidate policies; fill-to-bracket and fill-to-IRMAA apply mechanical caps; fixed-dollar uses the entered annual amount; none allows only forced conversions.',consider:'Use optimize_terminal_tax for the normal default so the workbook explains the selected strategy.'};
  if(l.includes('roth_target_bracket_rate'))return {purpose:'Sets the marginal tax bracket ceiling for fill-to-bracket Roth conversion strategies.',impact:'Higher brackets allow larger conversions but may increase current tax, IRMAA risk, and cash-flow strain.',consider:'Use this as a ceiling, not a mandate. The 95% headroom setting prevents filling exactly to the dollar.'};
  if(l.includes('forced')||l.includes('roth_conversion_wife_ira_to_roth'))return {purpose:'Records a user-directed or already-executed Roth conversion that the optimizer should not choose or remove.',impact:'Forced conversions appear separately from voluntary optimizer conversions and still affect AGI, taxes, Medicare thresholds, and account balances.',consider:'Use forced rows only for confirmed actions or explicit scenario assumptions.'};
  return null;
}
function showSectionHelp(ev,btn){if(ev){ev.preventDefault();ev.stopPropagation();}const d=btn?.closest?.('details.cfg-section');if(!d)return;const box=document.getElementById('adminHelp');const title=d.dataset.helpTitle||'Setting group';const note=d.dataset.helpNote||'Review this setting group before saving. Changes flow into the workbook and reports.';if(box)box.innerHTML=`<div class="help-title">${esc(title)}</div><div class="help-body"><h3>What this group controls</h3><p>${esc(note)}</p><h3>How the settings work together</h3><p>Rows in the same group are usually read together during build, pricing, tax, optimizer, diagnostics, or report generation. Review related settings before changing a single row in isolation.</p><h3>How to choose values</h3><p>Use row-level help for the exact option meaning. Save after edits, then rebuild or restart only when the setting itself requires it.</p><h3>Likely planning or system impact</h3><p>Changing this group can affect cash flow, terminal net worth, lifetime taxes, post-terminal taxes, risk, workbook narratives, warnings, recommendations, pricing reliability, or app behavior.</p></div>`;d.open=true;}
function showSettingHelpFromControl(ctrl){showSettingHelp(null,ctrl)}

function adminNorm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'_')}
function adminValueOptionsHelp(key,units,value){const k=adminNorm(key),u=String(units||''),v=String(value||'');if(/yes\/no|true\/false/i.test(u)||/^(YES|NO|TRUE|FALSE)$/i.test(v))return '<ul><li><b>YES</b>: enable or include this behavior in the system/build.</li><li><b>NO</b>: disable or exclude this behavior.</li></ul>';if(k.includes('pricing_mode'))return '<ul><li><b>LIVE</b>: request fresh provider quotes and cache them when available.</li><li><b>CACHE</b>: use saved cached quotes first, then fallback only when needed.</li><li><b>OFFLINE</b>: avoid external calls and use local/fallback values.</li></ul>';if(k.includes('max_build_seconds')||k.includes('timeout'))return '<p>Use seconds. Higher values let long Monte Carlo/workbook builds finish; lower values fail faster when a build is stuck.</p>';if(k.includes('percent')||k.endsWith('_pct')||u.includes('%'))return '<p>Use a percentage. Higher values magnify the related inflation, return, guardrail, allocation, tax, or risk assumption.</p>';if(k.includes('amount')||k.includes('value')||k.includes('balance')||k.includes('tax')||k.includes('income')||k.includes('spending')||u.includes('$'))return '<p>Use dollars. Higher values usually increase the modeled amount; whether that helps or hurts depends on whether this is income/asset or tax/expense/liability.</p>';if(u)return `<p>Expected format: ${esc(units)}.</p>`;return '<p>Use the value that matches the documented system assumption, reference-data source, or operational setting.</p>'}
function adminConnectionHelp(key,location){const k=adminNorm(key),loc=String(location||'');if(k.includes('pricing'))return 'Connects to holdings values, allocation drift, tax-lot estimates, rebalancing recommendations, and pricing diagnostics.';if(k.includes('tax'))return 'Connects to tax schedules, Roth scoring, lifetime tax, estate-tax exposure, and QC freshness warnings.';if(k.includes('build')||k.includes('timeout'))return 'Connects to UI build reliability, Monte Carlo completion, workbook/PDF generation, and final plan_summary output.';if(k.includes('allocation')||k.includes('optimizer')||k.includes('trade'))return 'Connects to recommended asset allocation, tax-aware trades, drift tolerance, turnover, and recommendation narratives.';if(k.includes('path')||k.includes('folder')||k.includes('csv'))return 'Connects to local file adapters, backup/recovery, import/export, and database mirroring.';return `Connects to the ${esc(loc||'current configuration area')} and may be read together with nearby settings during the next build.`}
function adminDefaultMeaning(key,note,units,location){const k=adminNorm(key),label=String(key||'setting').replace(/_/g,' '),loc=String(location||'System Configuration');const cleanNote=String(note||'').trim();if(cleanNote&&cleanNote!=='This value is used by workbook generation, planning logic, or recommendation output.')return cleanNote;if(k.includes('pricing'))return `Controls how market values are obtained or reused for holdings in ${loc}. This affects whether account values come from live quotes, cached quotes, or local fallback data.`;if(k.includes('timeout')||k.includes('max_build_seconds'))return `Sets how long the local build process may run before the UI treats it as failed. Longer values give Monte Carlo, workbook, PDF, and dashboard generation more time to finish.`;if(k.includes('path')||k.includes('folder')||k.includes('csv'))return `Identifies a local file or adapter location used for import, export, diagnostics, or recovery while the SQLite database remains the primary source of truth.`;if(k.includes('tax')||k.includes('bracket')||k.includes('deduction'))return `Provides a tax-reference assumption used to calculate projected income taxes, lifetime taxes, Roth strategy comparisons, estate-tax exposure, or QC freshness warnings.`;if(k.includes('roth'))return `Controls a Roth conversion setting that can change current-year taxable income, future RMDs, Medicare threshold exposure, survivor taxation, and Roth legacy scoring.`;if(k.includes('allocation')||k.includes('optimizer')||k.includes('trade'))return `Controls optimizer or rebalancing behavior used to translate holdings and assumptions into target allocation, drift, recommended trades, turnover, and tax-aware trade limits.`;if(k.includes('enabled')||k.includes('toggle')||k.startsWith('include'))return `Turns a module, report element, diagnostic, or calculation path on or off for future builds.`;if(String(units||'').includes('$'))return `Sets a dollar-denominated system assumption named ${label}. The build reads it as a monetary limit, threshold, fallback value, or model input depending on its configuration group.`;if(String(units||'').includes('%')||k.includes('pct')||k.includes('rate'))return `Sets a percentage-based system assumption named ${label}. The build uses it to scale rates, limits, guardrails, returns, inflation, taxes, or optimizer weights.`;return `Controls the ${label} setting in ${loc}. The next save/rebuild uses it together with nearby settings to shape generated outputs, diagnostics, recommendations, or local runtime behavior.`}
function adminImpactHelp(key,note,units){const k=adminNorm(key);let directional='';if(k.includes('timeout'))directional='Higher timeout values reduce false build failures but can make a truly stuck build take longer to report.';else if(k.includes('pricing_mode'))directional='LIVE can improve current values but depends on provider availability; CACHE is more stable for routine work; OFFLINE is safest for no-network validation but may use fallback values.';else if(k.includes('enabled')||k.includes('toggle'))directional='Changing No to Yes usually exposes a module or calculation in outputs; changing Yes to No usually removes it from reports and diagnostics.';else if(k.includes('tax'))directional='Tax-reference changes can move lifetime taxes, Roth recommendations, estate exposure, and QC warnings.';else directional='Changing this value can affect TNW, lifetime taxes, interim liquidity, recommendations, warnings, or system reliability after save/rebuild.';return [note,directional].filter(Boolean).join(' ')}
function showSettingHelp(ev,btn){
  if(ev){ev.preventDefault();ev.stopPropagation();}
  const box=document.getElementById('adminHelp');
  const title=btn?.dataset?.helpTitle||'Setting';
  const key=btn?.dataset?.helpKey||'';
  const units=btn?.dataset?.helpUnits||'';
  const note=btn?.dataset?.helpNote||'This value is used by workbook generation, planning logic, or recommendation output.';
  const location=btn?.dataset?.helpLocation||'';
  const g=adminFieldGuidance(key,note,units,location)||{};
  const meaning=g.purpose||adminDefaultMeaning(key,note,units,location);
  const options=g.options||adminValueOptionsHelp(key,units,btn?.value||'');
  const connections=g.connections||adminConnectionHelp(key,location);
  const impact=g.impact||adminImpactHelp(key,note,units);
  if(box)box.innerHTML=`<div class="help-title">${esc(title)}</div><div class="help-body"><h3>What this value means</h3><p>${esc(meaning)}</p><h3>Value options and how to choose</h3>${options}<h3>How it relates to this page</h3><p>${connections}</p><h3>Likely impact of changing it</h3><p>${impact.includes('<')?impact:esc(impact)}</p></div>`;
  const d=btn?.closest?.('details.cfg-section');if(d)d.open=true;
}
function showColumnHelp(ev,btn){if(ev){ev.preventDefault();ev.stopPropagation();}const box=document.getElementById('adminHelp');const col=btn?.dataset?.col||'Column';const note=btn?.dataset?.note||'Editable CSV adapter column.';if(box)box.innerHTML=`<div class="help-title">${esc(titleCaseLabel(col))}</div><div class="help-body"><h3>What this column means</h3><p>${esc(note)}</p><h3>Value options and how to choose</h3><p>Use values consistent with the column purpose and the other columns in the same row. For choice-like columns, keep spelling consistent so downstream lookups match.</p><h3>How it relates to this table</h3><p>Columns in the same row are read together. A good value in one column can be ignored or misclassified if the account, ticker, source, date, or category columns around it are inconsistent.</p><h3>Likely impact of changing it</h3><p>Column edits can affect classifications, pricing, tax treatment, optimizer behavior, YTD mapping, warnings, or report totals depending on this reference table.</p></div>`;}
function tableColumnNote(profile,col){const p=COLUMN_HELPERS[profile]||{};return p[col]||({section:'Grouping section. Keeps related inputs together.',subsection:'Subgroup within the section.',label:'Setting key used by the model.',value:'Editable value used by workbook/projection logic.',units:'Expected type or units.',notes:'Helper note explaining the setting impact.'}[col]||'Editable field. Review downstream workbook impact before saving.');}
function gridChoicesFor(profile,col,row,head){const c=String(col||'').toLowerCase();if(c==='type')return ['text','choice','boolean','date','percent','integer','year','number','currency','dollars','path','secret','covered'];if(['required','exempt_retirement','exempt_ss','estate','blocking'].includes(c))return ['TRUE','FALSE'];if(c==='status')return ['CURRENT_WITHIN_POLICY','REVIEW_REQUIRED','STALE','UNKNOWN'];return null;}
function gridControl(profile,h,row,ri,ci,head){const choices=gridChoicesFor(profile,h,row,head);const val=row[ci]||'';if(choices){return `<select class="grid-input" data-row="${ri+1}" data-col="${ci}" onchange="markGridChanged(this)">${choices.map(c=>`<option value="${esc(c)}" ${String(c)===String(val)?'selected':''}>${esc(c)}</option>`).join('')}<option value="${esc(val)}" ${choices.includes(val)?'':'selected'}>${choices.includes(val)?'':'Custom: '+esc(val)}</option></select>`}return `<input class="grid-input" data-row="${ri+1}" data-col="${ci}" value="${esc(val)}" oninput="markGridChanged(this)">`;}
function buildDataGrid(rows,profile='generic'){if(!rows.length)return '<div class="no-results">No rows found.</div>';const head=rows[0];const body=rows.slice(1);return `<div class="scroll"><table class="data-table"><thead><tr>${head.map((h,ci)=>`<th>${esc(titleCaseLabel(h))} <button type="button" class="column-help-btn" title="Column help" aria-label="Help for ${esc(h)}" data-col="${esc(h)}" data-note="${esc(tableColumnNote(profile,h))}" onclick="showColumnHelp(event,this)">?</button></th>`).join('')}<th>Actions</th></tr></thead><tbody>${body.map((r,ri)=>`<tr data-filter="${esc(r.join(' ').toLowerCase())}">${head.map((h,ci)=>`<td>${gridControl(profile,h,r,ri,ci,head)}</td>`).join('')}<td><button class="danger" onclick="deleteGridRow(${ri+1})">Delete</button></td></tr>`).join('')}</tbody></table></div><button onclick="addGridRow()">Add row</button>`;}
function summarizeRows(rows){const settings=rows.filter(isSetting);const sections=new Set(settings.map(r=>rowCell(r,0)));const pricing=settings.find(r=>rowCell(r,2)==='pricing_mode');const opt=settings.find(r=>rowCell(r,2)==='trade_optimizer_mode');return `<div class="cfg-summary"><div class="summary-card"><span class="muted">Sections</span><b>${sections.size}</b></div><div class="summary-card"><span class="muted">Editable settings</span><b>${settings.length}</b></div><div class="summary-card"><span class="muted">Pricing mode</span><b>${esc(pricing?rowCell(pricing,3):'n/a')}</b></div><div class="summary-card"><span class="muted">Trade optimizer</span><b>${esc(opt?rowCell(opt,3):'n/a')}</b></div></div>`;}
function markActiveChanged(el){const i=Number(el.dataset.row);while(activeEditor.rows[i].length<6)activeEditor.rows[i].push('');activeEditor.rows[i][3]=el.value;el.classList.add('changed');activeEditor.changed=true;if(activeEditor.file==='system_config.csv')sysCfgChanged=true;msg('Unsaved changes in '+activeEditor.title);}
function markGridChanged(el){const r=Number(el.dataset.row),c=Number(el.dataset.col);while(activeEditor.rows[r].length<=c)activeEditor.rows[r].push('');activeEditor.rows[r][c]=el.value;el.classList.add('changed');activeEditor.changed=true;msg('Unsaved changes in '+activeEditor.title);}
function filterActiveTable(){const cfgEl=document.getElementById('cfgSearch');if(cfgEl&&adminSearchScope==='page')adminPageSearchText=cfgEl.value;const q=(adminSearchScope==='page'?adminPageSearchText:(cfgEl?.value||'')).trim().toLowerCase();let visible=0;document.querySelectorAll('#editorBody tr[data-filter]').forEach(tr=>{const show=!q||tr.dataset.filter.includes(q);tr.style.display=show?'':'none';if(show)visible++;});document.querySelectorAll('#editorBody details.cfg-section').forEach(d=>{const rows=[...d.querySelectorAll('tr[data-filter]')];const any=rows.some(r=>r.style.display!=='none');d.style.display=any?'':'none';if(q&&any)d.open=true;});const cnt=document.getElementById('cfgResultCount');if(cnt)cnt.textContent=`${visible} matching rows`;applyEditorHeadingPage(q?null:0,false);}
function editorDetails(){return [...document.querySelectorAll('#editorBody details.cfg-section')];}
function applyEditorHeadingPage(page=0,scroll=true){const details=editorDetails();if(!details.length)return;if(details.length<=8){details.forEach(d=>{d.dataset.pageHidden='0';if(!d.hasAttribute('data-filter-hidden'))d.style.display='';});activeEditorHeadingPage=0;updateEditorHeadingNavPages();return;}activeEditorHeadingPage=Math.max(0,Math.min(page,Math.ceil(details.length/8)-1));details.forEach((d,i)=>{const show=Math.floor(i/8)===activeEditorHeadingPage;d.dataset.pageHidden=show?'0':'1';d.style.display=show?'':'none';});updateEditorHeadingNavPages();const visible=details.filter(d=>d.style.display!=='none');if(scroll)document.getElementById('editorBody')?.scrollIntoView({behavior:'smooth',block:'start'});}
function editorParentStep(){return activeEditor?.navStep||activeAdminStep;}
function clearEditorHeadingNavPages(){editorHeadingNavPages=[];renderAdminNav();}
function updateEditorHeadingNavPages(){const details=editorDetails();if(!details.length||details.length<=8){editorHeadingNavPages=[];renderAdminNav();return;}const pages=Math.ceil(details.length/8);const parent=editorParentStep();const parentItem=(lastAdminNavItems||[]).find(x=>x.id===parent)||{};editorHeadingNavPages=Array.from({length:pages},(_,i)=>{const start=i*8+1,end=Math.min(details.length,(i+1)*8);return {id:`${parent}_headings_${i}`,group:parentItem.group||'Current editor',title:`${parentItem.title||activeEditor?.title||'Editor'} · headings ${start}-${end}`,desc:'Additional collapsible heading page in the left navigation',action:`showEditorHeadingPage(${i})`,helpKey:navHelpKey(parent)}});renderAdminNav();}
function showEditorHeadingPage(page){applyEditorHeadingPage(page,false);const id=`${editorParentStep()}_headings_${page}`;setAdminStep(id);document.getElementById('editorBody')?.scrollIntoView({behavior:'smooth',block:'start'});}
function initEditorInteractions(){const details=editorDetails();if(!details.length){clearEditorHeadingNavPages();return;}details.forEach((d,idx)=>{const summary=d.querySelector('summary');const focusables=[...d.querySelectorAll('input,select,textarea,button,a,[tabindex]:not([tabindex="-1"])')].filter(el=>el!==summary&&!el.disabled);const last=focusables[focusables.length-1];if(last){last.addEventListener('keydown',ev=>{if(ev.key==='Tab'&&!ev.shiftKey){const next=details[idx+1];if(next){if(next.dataset.pageHidden==='1')applyEditorHeadingPage(Math.floor((idx+1)/8),false);next.open=true;}}});}});applyEditorHeadingPage(0,false);}
function toggleRawEditor(){const box=document.getElementById('rawBox');box.classList.toggle('open');if(box.classList.contains('open'))document.getElementById('rawCsv').value=rowsToCsv(activeEditor.rows);}
async function loadCsvEditor(def,backAction='showAppSettings()'){const out=await api(`/api/admin/csv-file/${encodeURIComponent(def.kind)}/${encodeURIComponent(def.file)}`);const rows=(out.rows&&out.rows.length?out.rows:parseCsv(out.csv_content||''));activeEditor={...def,rows,route:`/api/admin/csv-file/${def.kind}/${def.file}`,title:def.title||def.file,changed:false,backAction};const isSection=rows[0]&&rowCell(rows[0],0).toLowerCase()==='section'&&rowCell(rows[0],1).toLowerCase()==='subsection';const body=isSection||def.profile==='section_settings'?buildSectionSettings(rows,def):buildDataGrid(rows,def.profile);document.getElementById('main').innerHTML=`<h2>${esc(activeEditor.title)}</h2><p class="muted">${esc(out.path)} · Compact table view. Changes save to the system configuration store and maintain CSV adapter compatibility.</p>${def.note?`<div class="note-box">${esc(def.note)}</div>`:''}<div class="toolbar compact-toolbar"><input id="cfgSearch" class="cfg-input hidden" placeholder="Search rows, values, or helper notes..." oninput="filterActiveTable()"><span id="cfgResultCount" class="pill">${Math.max(0,rows.length-1)} rows</span><span><button onclick="document.querySelectorAll('#editorBody details').forEach(d=>d.open=true)">Expand all</button><button onclick="document.querySelectorAll('#editorBody details').forEach(d=>d.open=false)">Collapse all</button><button onclick="toggleRawEditor()">Advanced raw CSV</button></span><div class="collapsed-note">Use the triangles to expand sections. Focus any value control to update the right help panel.</div></div><div id="editorBody">${body}</div><div id="rawBox" class="advanced-box"><h3>Advanced CSV adapter editor</h3><p class="muted">Use only for bulk adapter maintenance or adding columns. Normal planning edits belong in the main UI.</p><textarea id="rawCsv">${esc(rowsToCsv(rows))}</textarea></div><div class="cfg-actions"><button class="primary" onclick="saveActiveEditor()">Save</button><button onclick="loadCsvEditor(activeEditor,activeEditor.backAction)">Reload from disk</button><span class="mini">Save stays visible. Use the left navigation to move between pages; raw CSV fallback is preserved.</span></div>`;initEditorInteractions();msg(activeEditor.title+' loaded');}
async function saveActiveEditor(){const rawOpen=document.getElementById('rawBox')?.classList.contains('open');const body=rawOpen?{csv_content:document.getElementById('rawCsv').value}:{rows:activeEditor.rows};await api(activeEditor.route,{method:'POST',body:JSON.stringify(body)});if(activeEditor.file==='system_config.csv')sysCfgChanged=false;activeEditor.changed=false;msg(activeEditor.title+' saved. Restart the app if you changed startup-only settings.');await loadCsvEditor(activeEditor,activeEditor.backAction);}
function addGridRow(){const cols=activeEditor.rows[0]?.length||1;activeEditor.rows.push(Array(cols).fill(''));loadCsvEditorFromMemory();}
function deleteGridRow(i){activeEditor.rows.splice(i,1);loadCsvEditorFromMemory();}
function loadCsvEditorFromMemory(){const def=activeEditor;const isSection=def.rows[0]&&rowCell(def.rows[0],0).toLowerCase()==='section';document.getElementById('editorBody').innerHTML=isSection?buildSectionSettings(def.rows,def):buildDataGrid(def.rows,def.profile);initEditorInteractions();def.changed=true;msg('Unsaved changes in '+def.title);}

const SYSTEM_CONFIG_PAGES=[
  {id:'runtime',title:'Runtime & files',desc:'Core version, config backend, file paths, output paths, and local Plan Data defaults.',filterSections:['System Configuration'],filterSubsections:['Runtime']},
  {id:'access',title:'App settings',desc:'Local dashboard host, port, build timeout, and local-only settings.',filterSections:['System Configuration'],filterSubsections:['Dashboard','Security']},
  {id:'jobs',title:'Refresh, drift & Plan Chat',desc:'Nightly refresh, drift thresholds, portfolio file links, and Plan Chat toggles.',filterSections:['System Configuration'],filterSubsections:['Price Refresh','Portfolio Drift','Plan Chat']},
  {id:'build_timeout',title:'Build timeout',desc:'Maximum build runtime before timeout. Increase this for exact scalar Monte Carlo or larger simulation counts.',filterSections:['System Configuration'],filterKeys:['max_build_seconds']},
  {id:'plan',title:'Plan settings',desc:'System-level annuity valuation, NIIT, and estate-tax model switches.',filterSections:['Plan Settings']},
  {id:'assumptions',title:'Capital-market assumptions',desc:'Expected returns, volatility, custom assumption files, and long-term optimizer inputs.',filterSections:['Asset Class Assumptions']},
  {id:'correlations',title:'Asset correlations',desc:'Pairwise correlation settings used by optimizer diversification calculations.',filterSections:['Asset Correlations']},
  {id:'rebalancing',title:'Global rebalancing controls',desc:'Household-level tax-aware optimizer mode, risk limits, tax-aware trade controls, and objective weights.',filterSections:['Rebalancing']}
];
function systemConfigPage(id){return SYSTEM_CONFIG_PAGES.find(p=>p.id===id)||SYSTEM_CONFIG_PAGES[0]}
function adminNavItems(){const items=[
  {id:'app_settings',group:'System setup',title:'App settings',desc:'Local host, port, build timeout, and start commands',action:'showAppSettings()',helpKey:'app_settings'}
];SYSTEM_CONFIG_PAGES.forEach(p=>items.push({id:'syscfg_'+p.id,group:'System configuration',title:p.title,desc:p.desc,action:`showSystemConfig('${p.id}')`,helpKey:'system_config'}));items.push(
  {id:'tax_law_dashboard',group:'Tax governance',title:'Tax-law update dashboard',desc:'Federal/state/IRMAA/Social Security/RMD constants, source, year, and review status',action:'showTaxLawDashboard()',helpKey:'tax'},
  {id:'pricing_controls',group:'Market data',title:'Pricing controls',desc:'CACHE, LIVE, OFFLINE, cache window, and provider settings',action:'openPricingControls()',helpKey:'pricing'},
  {id:'pricing_security',group:'Market data',title:'Security master',desc:'Ticker mapping, ETF universe, and asset-class mapping',action:'openSecurityMaster()',helpKey:'pricing'},
  {id:'diagnostics',group:'Operations',title:'Workbook build diagnostics',desc:'Last build source, QC, forecast package status',action:'showDiagnostics()',helpKey:'diagnostics'}
);Object.entries(AREA_DEFS||{}).forEach(([areaId,area])=>{const group={allocation:'Investment policy',optimizer:'Investment policy',etf:'Market data',accountsTax:'Tax & accounts',household:'Planning inputs',optional:'Workbook options'}[areaId]||area.title;(area.files||[]).forEach((f,idx)=>items.push({id:`area_${areaId}_${idx}`,group,title:f.title,desc:area.title,action:`openAreaFile('${areaId}',${idx})`,helpKey:areaId}));});items.push(
  {id:'reference',group:'Reference data',title:'Reference files',desc:'System-wide tax, market, schema, and security tables',action:'showReferenceFiles()',helpKey:'reference'}
);return items;}
function renderAdminNav(){const box=document.getElementById('adminSteps');if(!box)return;lastAdminNavItems=adminNavItems();let items=[...lastAdminNavItems,...editorHeadingNavPages];const q=String(adminNavSearchText||'').trim().toLowerCase();if(q){items=items.filter(it=>[it.id,it.group,it.title,it.desc,it.file].join(' ').toLowerCase().includes(q)||it.id===activeAdminStep)}let lastGroup='',stepNo=0;box.classList.add('grouped');box.innerHTML=items.map((it)=>{const group=it.group||'Current editor';const label=group!==lastGroup?`<div class="nav-group-label">${esc(group)}</div>`:'';if(group!==lastGroup)lastGroup=group;stepNo++;return `${label}<button class="stepbtn ${it.id===activeAdminStep?'active':''}" data-admin-step="${esc(it.id)}" onclick="${it.action}"><span class="num">${stepNo}</span><span><span class="step-title">${esc(it.title)}</span><div class="step-desc">${esc(it.desc||'Open this page')}</div></span></button>`;}).join('')||'<div class="no-results">No navigation matches.</div>';}
function setAdminNavSearch(q){adminNavSearchText=q;renderAdminNav()}
function updateAdminSearchToggle(){const el=document.getElementById('adminCombinedSearch');if(el){el.value=adminSearchScope==='nav'?adminNavSearchText:adminPageSearchText;el.placeholder=adminSearchScope==='nav'?'Search navigation...':'Search this page...'}document.querySelectorAll('[data-admin-search-scope]').forEach(b=>b.classList.toggle('primary',b.dataset.adminSearchScope===adminSearchScope))}
function setAdminSearchScope(scope){adminSearchScope=scope==='page'?'page':'nav';updateAdminSearchToggle();if(adminSearchScope==='page')filterActiveTable();else renderAdminNav()}
function setAdminCombinedSearch(q){if(adminSearchScope==='nav'){adminNavSearchText=q;renderAdminNav()}else{adminPageSearchText=q;const cfg=document.getElementById('cfgSearch');if(cfg)cfg.value=q;filterActiveTable()}updateAdminSearchToggle()}
async function showSystemConfig(pageId='runtime'){const page=systemConfigPage(pageId);setAdminStep('syscfg_'+page.id);const def={kind:'system',file:'system_config.csv',title:page.title,profile:'section_settings',filterSections:page.filterSections||[],filterSubsections:page.filterSubsections||[],defaultOpen:false,collapseBySubsection:true,note:page.desc+' Changes save back to system_config.csv.',navStep:'syscfg_'+page.id};await loadCsvEditor(def,`showSystemConfig('${page.id}')`);sysCfgRows=activeEditor.rows;sysCfgOriginal=rowsToCsv(sysCfgRows);sysCfgChanged=false;const h=document.querySelector('#main h2');if(h)h.insertAdjacentHTML('afterend',summarizeRows(filteredSettingRows(sysCfgRows,def).map(x=>x.r)));}
async function openAreaFile(id,idx){const area=AREA_DEFS[id];const def={...area.files[idx],navStep:`area_${id}_${idx}`};setAdminStep(def.navStep);await loadCsvEditor(def,`openAreaFile('${id}',${idx})`)}
async function showArea(id){await openAreaFile(id,0)}
async function openPricingControls(){setAdminStep('pricing_controls');await loadCsvEditor({kind:'system',file:'system_config.csv',title:'Pricing controls',profile:'section_settings',filterSections:['Market Pricing'],defaultOpen:false,note:'LIVE tries quote providers first; CACHE uses cached prices even when stale before live calls; OFFLINE avoids live calls.',navStep:'pricing_controls'},'openPricingControls()');renderPricingSymbolTester()}

function renderPricingSymbolTester(){
  const main=document.getElementById('main');
  if(!main||document.getElementById('pricingSymbolTester'))return;
  const html=`<div id="pricingSymbolTester" class="note-box" style="margin:0 0 14px 0">
    <h3 style="margin-top:0">Single-symbol live pricing tester</h3>
    <p class="muted">Enter one ticker and this will call each live provider directly, bypassing cache selection for the diagnostic. It prints the redacted command sent to each service plus response status, timing, preview, parser result, and final provider selection.</p>
    <div class="row"><input id="pricingTestSymbol" placeholder="Ticker, e.g. VTI" style="max-width:220px;text-transform:uppercase" onkeydown="if(event.key==='Enter')runLivePriceSymbolTest()"><button class="primary" onclick="runLivePriceSymbolTest()">Test live quote</button><span id="pricingTestStatus" class="muted"></span></div>
    <div id="pricingTestResult" style="margin-top:12px"></div>
  </div>`;
  const pane=main.querySelector('.pane-head');
  if(pane)pane.insertAdjacentHTML('afterend',html);else main.insertAdjacentHTML('afterbegin',html);
}
function fmtPriceDiagnostic(v){const n=Number(v);return Number.isFinite(n)&&n>0?'$'+n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:4}):esc(v??'')}
function renderJsonBlock(obj){return `<pre class="code" style="display:block;white-space:pre-wrap;max-height:260px;overflow:auto;margin:6px 0">${esc(JSON.stringify(obj,null,2))}</pre>`}
function renderProviderAttempt(a){return `<div class="diag-card" style="margin:8px 0;background:${a.ok?'#f0fdf4':'#fff7ed'}"><div class="row"><b>${esc(a.transport||'transport')}</b><span class="pill">${a.ok?'ok':'failed'}</span>${a.status_code?`<span class="pill">HTTP ${esc(a.status_code)}</span>`:''}<span class="pill">${esc(a.elapsed_ms??'')} ms</span>${a.content_type?`<span class="pill">${esc(a.content_type)}</span>`:''}</div><h4>Command sent</h4>${renderJsonBlock(a.command||{})}${a.cause?`<h4>Failure cause</h4><p class="muted">${esc(a.cause)}</p>`:''}${a.exception?`<h4>Exception</h4><p class="muted">${esc(a.exception)}</p>`:''}${a.response_preview?`<h4>Response preview</h4><pre class="code" style="display:block;white-space:pre-wrap;max-height:180px;overflow:auto">${esc(a.response_preview)}</pre>`:''}</div>`}
function renderProviderStep(s){const ok=s.outcome==='success';const skipped=s.outcome==='skipped'||s.enabled===false;return `<details class="cfg-section" ${ok||!skipped?'open':''}><summary><span class="summary-title">${esc(s.provider||'provider')} · ${esc(s.endpoint||'endpoint')}</span><span class="badge ${ok?'ok':skipped?'warn':'bad'}">${esc(s.outcome||'unknown')}</span></summary><div style="padding:12px"><div class="diag-grid"><div class="diag-card"><b>Parsed price</b><p>${s.parsed_price?fmtPriceDiagnostic(s.parsed_price):'—'}</p></div><div class="diag-card"><b>Parser note</b><p class="muted">${esc(s.parse_note||'')}</p></div><div class="diag-card"><b>Cause</b><p class="muted">${esc(s.cause||'')}</p></div></div>${(s.attempts||[]).map(renderProviderAttempt).join('')}${(!s.attempts||!s.attempts.length)?`<p class="muted">${esc(s.cause||'No command was sent for this provider.')}</p>`:''}</div></details>`}
function renderPricingSymbolTrace(r){const steps=r.steps||[];return `<div class="section-note"><b>${esc(r.symbol||'')}</b> — ${esc(r.summary||'No summary')}</div><div class="diag-grid"><div class="diag-card"><b>Selected live provider</b><p>${esc(r.selected_provider||'none')}</p></div><div class="diag-card"><b>Selected price</b><p>${r.selected_price?fmtPriceDiagnostic(r.selected_price):'—'}</p></div><div class="diag-card"><b>Provider order</b><p class="muted">${esc((r.provider_order||[]).join(' → '))}</p></div><div class="diag-card"><b>Proxy/cert environment</b><p class="muted">${r.proxy_environment_present?'Present: '+esc((r.proxy_environment_keys||[]).join(', ')):'None detected'}</p></div></div><details class="cfg-section" open><summary><span class="summary-title">Runtime and key diagnostics</span></summary><div style="padding:12px">${renderJsonBlock({generated_at_utc:r.generated_at_utc,config_backend:r.config_backend,config_path:r.config_path,workspace_id:r.workspace_id,timeout_seconds:r.timeout_seconds,max_retries:r.max_retries,requests_available:r.requests_available,effective_api_key_sources:r.effective_api_key_sources,cache_record:r.cache_record})}</div></details><h3>Provider command / response trace</h3>${steps.map(renderProviderStep).join('')||'<div class="no-results">No provider steps returned.</div>'}`}
async function pollLivePriceSymbolJob(jobId,status,result){for(let i=0;i<240;i++){await new Promise(r=>setTimeout(r,500));const out=await api('/api/prices/test-symbol/status/'+encodeURIComponent(jobId),{timeoutMs:9000});const trace=out.result||{symbol:out.symbol,summary:'Calling live providers...',steps:out.steps||[]};if(out.steps&&(!trace.steps||!trace.steps.length))trace.steps=out.steps;if(result)result.innerHTML=renderPricingSymbolTrace(trace);const count=(trace.steps||[]).length;if(status)status.textContent=out.status==='running'?`Calling live providers... ${count} step${count===1?'':'s'} returned`:out.status==='completed'?(out.live_pricing_working?'Live quote found':'No live quote found'):'Diagnostic error';if(out.status==='completed'||out.status==='error')return out}throw new Error('Pricing tester timed out waiting for the local diagnostic job. A provider call may still be running; try a shorter timeout in Market Pricing settings.')}
async function runLivePriceSymbolTest(){const input=document.getElementById('pricingTestSymbol');const status=document.getElementById('pricingTestStatus');const result=document.getElementById('pricingTestResult');const symbol=(input?.value||'').trim().toUpperCase();if(!symbol){msg('Enter one ticker symbol first');return}if(status)status.textContent='Starting diagnostic...';if(result)result.innerHTML='<div class="section-note">Starting local diagnostic job. Provider commands and responses will appear as each service returns.</div>';try{const started=await api('/api/prices/test-symbol/start',{method:'POST',body:JSON.stringify({symbol}),timeoutMs:9000});if(status)status.textContent='Calling live providers...';const out=await pollLivePriceSymbolJob(started.job_id,status,result);const liveOk=!!(out.live_pricing_working||(out.result&&out.result.success));msg(liveOk?'Live pricing tester found a quote':'Live pricing tester completed with failures')}catch(e){const detail=String(e&&e.message||e||'Unknown error');if(result)result.innerHTML=`<div class="section-note warn"><b>Pricing tester could not reach the local API.</b><br>${esc(detail)}<br><br>Endpoint: <code>/api/prices/test-symbol/start</code>. If the browser says "Failed to fetch", restart the app and confirm the status indicator shows Ready.</div>`;if(status)status.textContent='Error';msg('Pricing tester error: '+detail)}}
async function openSecurityMaster(){setAdminStep('pricing_security');await loadCsvEditor({kind:'reference',file:'security_master.csv',title:'Security master / ETF universe',profile:'security_master',note:'Ensure symbols and asset classes are correct before relying on recommendations.',navStep:'pricing_security'},'openSecurityMaster()')}
async function showPricingAdmin(){await openPricingControls()}


async function showTaxLawDashboard(){setAdminStep('tax_law_dashboard');const out=await api('/api/admin/tax-law-dashboard');document.getElementById('main').innerHTML=`<h2>Tax-law update dashboard</h2><p class="muted">Every tax-sensitive output must identify constant vintage, source, last reviewed date, and whether it is blocking advisor-ready status.</p><table><tr><th>Constant</th><th>Category</th><th>Year</th><th>Source</th><th>Last reviewed</th><th>Status</th></tr>${(out.rows||[]).map(r=>`<tr><td>${esc(r.constant)}</td><td>${esc(r.category)}</td><td>${esc(r.year)}</td><td>${esc(r.source)}</td><td>${esc(r.last_reviewed)}</td><td><span class="badge ${r.blocking?'bad':'ok'}">${esc(r.status)}</span></td></tr>`).join('')}</table><div class="section-note">Blocking means the report may still be illustrative, but advisor-ready/recommendation status is not allowed until updated or signed off.</div>`;msg('Tax-law dashboard loaded')}
async function showAdvisorSignoff(){setAdminStep('reference');document.getElementById('main').innerHTML=`<h2>Assumption review moved</h2><p class="muted">Plan assumption review is handled in the User UI Review section so it stays connected to plan outputs. It is not mandatory signoff language.</p>`;msg('Assumption review is in the User UI')}

async function showDiagnostics(){setAdminStep('diagnostics');const out=await api('/api/admin/diagnostics');document.getElementById('main').innerHTML=`<h2>Workbook build diagnostics</h2><p class="muted">${esc(out.output_dir)} · Last generated local output files.</p><div class="diag-grid">${out.files.map(f=>`<div class="diag-card"><b>${esc(f.name)}</b><p class="muted">${esc(f.path)}</p><span class="pill ${f.available?'good':'bad'}">${f.available?'available':'missing'}</span><span class="pill">${esc(f.bytes)} bytes</span>${f.json?`<h4>Summary</h4><pre class="code" style="white-space:pre-wrap;display:block;max-height:220px;overflow:auto">${esc(JSON.stringify(summarizeDiagnostic(f.json),null,2))}</pre>`:''}</div>`).join('')}</div>`;msg('Diagnostics loaded')}
function summarizeDiagnostic(j){if(!j||typeof j!=='object')return j;const keep=['pricing_source_summary','pricing_source_category','pricing_source_note','pricing_mode','live_enabled','cache_as_of_local','cache_as_of_utc','source_counts','qc_summary','build_time_utc','allocation_recommendation_source','trade_optimizer_mode'];const o={};keep.forEach(k=>{if(j[k]!==undefined)o[k]=j[k];});return Object.keys(o).length?o:j;}
async function showReferenceFiles(){setAdminStep('reference');const out=await api('/api/admin/reference-files');document.getElementById('main').innerHTML=`<h2>All reference files</h2><p class="muted">System-side reference inputs. Use compact editors for tabular files and raw fallback for bulk changes.</p><table><tr><th>File</th><th>Bytes</th><th>Impact</th><th>Actions</th></tr>${out.files.map(f=>`<tr><td>${esc(f.name)}</td><td>${f.bytes}</td><td class="impact">${esc(referenceImpact(f.name))}</td><td><button onclick="loadCsvEditor({kind:'reference',file:'${esc(f.name)}',title:'${esc(f.name)}',profile:profileForFile('${esc(f.name)}'),note:referenceImpact('${esc(f.name)}')},'showReferenceFiles()')">Compact edit</button></td></tr>`).join('')}</table>`;msg('Reference files loaded')}
function referenceImpact(name){return {security_master:'Ticker-to-asset-class mapping for holdings, ETF ideas, and recommended trades.',capital_market_assumptions:'Expected return and risk inputs for optimizer recommendations.',asset_correlations:'Diversification/covariance assumptions used by optimizer calculations.',schema:'Validation metadata and helper notes for client Plan Data.',state_tax:'State tax assumptions used in residency and tax projections.',tax_constants:'Federal tax thresholds, deductions, and constants.'}[name]||'Reference input used by workbook generation.'}
function profileForFile(name){if(name==='security_master.csv')return 'security_master';if(name==='capital_market_assumptions.csv')return 'capital_market';if(name==='tax_constants.csv')return 'tax_constants';return 'generic'}
async function showWorkspaces(){setAdminStep('app_settings');document.getElementById('main').innerHTML=`<h2>Local-only package</h2><p class="muted">Client registry and report browsing pages were removed. Use the User UI to edit the single local Plan Data folder and the download buttons after a build to retrieve reports.</p>`;msg('Local-only package: client registry removed')}
async function showWorkspaceFiles(t){showWorkspaces()}
async function editWorkspacePlanData(t,name){msg('Client Plan Data editing has moved to the User UI. Admin shows Plan Data read-only by default.');return false;}
window.addEventListener('beforeunload',e=>{if(sysCfgChanged||(activeEditor&&activeEditor.changed)){e.preventDefault();e.returnValue='Unsaved changes';}});
renderAdminNav();showAppSettings().catch(e=>msg('Error: '+e.message));updateAdminSearchToggle();checkApp();setInterval(checkApp,5000);
